### ISSUE TITLE
[ENH] Support Python 3.10

### ISSUE THREAD

**Issue by freddyaboulton** [alan-turing-institute/sktime#2079] opened 2022-02-17 17:18 UTC
**Is your feature request related to a problem? Please describe.**
sktime cannot be installed in python 3.10 because the [pyproject.toml](https://github.com/alan-turing-institute/sktime/blob/main/pyproject.toml#L44) file lists python<3.10 as a dependency.

**Describe the solution you'd like**
We should let users install sktime in python 3.10. 

Related issue: https://github.com/alkaline-ml/pmdarima/issues/481

**Comment by aiwalter** [comment] 2022-02-17 17:42
But then we need an Actions workflow for it as well. Jus removing the threshold is a bit risky

**Comment by freddyaboulton** [comment] 2022-02-17 17:45
Absolutely. This issue tracks all the work necessary to support python 3.10. I agree regularly testing the code in python version 3.10 is a requirement for that.

**Comment by lmmentel** [comment] 2022-02-20 18:19
I bumped the python version in `pyproject.toml` and updated the GH actions but  the current version of `pystan` does not compile under python 3.10.2 :(

**Comment by lmmentel** [comment] 2022-02-20 18:25
Prophet still depends on [pystan~=2.19.1.1](https://github.com/facebook/prophet/blob/main/python/requirements.txt) so this is blocked until:

- prophet bumps the pystan version that *might* compile against the python 3.10
- we figure out a way of compiling pystan against python 3.10
- we find a way of running a test suite without prophet

There might be some alternative solutions as well.

**Comment by freddyaboulton** [comment] 2022-02-20 18:33
@lmmentel thanks for looking into this!

I like the third option you propose. We can add a “skip_if_py310” marker that will automatically skip (or xfail) a test if it’s running in python 3.10 and use that to mark the prophet tests. pmdarima will support 3.10 in the next release so we can use the same marker to skip those tests until then. 

I like that because prophet is not a required dependency so I don’t think it should block our progress.  The prophet team is experimenting with pre-built wheels, so hopefully we won’t have to worry about compiling pystan in our ci long-term.

**Comment by lmmentel** [comment] 2022-02-20 19:10
OK, I think I should've been a bit clearer. Running tests is not a concern at this point since the previous step which installs `sktime` with `all_extras` fails when compiling `pystan` on python 3.10. Without being able to install the package we won't be able to test.

**Comment by freddyaboulton** [comment] 2022-02-20 19:36
Can we use a python_version < 3.10 environment marker on pystan/prophet in the toml file so that they’re not installed when installing all_extras?

**Comment by lmmentel** [comment] 2022-02-20 19:45
> Can we use a python_version < 3.10 environment marker on pystan/prophet in the toml file so that they’re not installed when installing all_extras?

I haven't seen that feature. Essentially it would mean different sets of dependencies for different python, not only the versions of dependencies but also the actual dependency items. Even if we were to somehow make it happen it might prove problematic to actually install the package.

I would probably be closer to dropping `prophet` or isolating it into a dependency group but then we would have to be able to run the test suite selectively without `prophet`.

**Comment by freddyaboulton** [comment] 2022-02-20 20:04
Here is an example of using environment markers. You put “, python_version < 3.10” after the dependency: https://www.python.org/dev/peps/pep-0631/#example

Yea I agree there would be some complexity with selectively skipping tests for prophet but it’s possible with pytest markers and I’ve seen that work well in the past.

**Comment by lmmentel** [comment] 2022-02-20 20:35
Thanks for the example @freddyaboulton, very helpful. I added the skip for prophet, pystan and esig. Obviously at this stage a lot the tests will break because of import errors.

**Comment by fkiraly** [comment] 2022-02-20 22:47
> I would probably be closer to dropping prophet or isolating it into a dependency group but then we would have to be able to run the test suite selectively without prophet.

We can do that easily if someone would finally be willing to review my test framework improvements 😁 
https://github.com/alan-turing-institute/sktime/pull/2023

**Comment by fkiraly** [comment] 2022-05-13 10:58
> Sorry, it was a badly phrased question. What I really wanted to ask was whether sktime will support 3.10? Most of the dependencies in pycaret now support this (with the latest release of sklearn) except sktime, so just curious :)

@ngupta23, moving the question from #2631 to here. Perhaps @lmmentel or @freddyaboulton can give you the newest on this?

**Comment by fkiraly** [comment] 2022-05-17 18:28
From discussion in #2651:

Why would non-3.10 compatible soft dependencies prevent us from an upgrade?

We can simply raise warnings and errors with a descriptive message regarding python compatibility, in those problematic soft dependencies? Might take a little bit of tinkering with the soft dependency utility, but surely soft dependencies should not prevent us from supporting python 3.10? That´s also not sustainable in the limit of infinite soft dependencies. I think we should generally decouple python support of sktime from that of soft dependencies.

On the technical side: imports happen only inside class methods, so in construction and class import we can raise the warning, without compromising functionality.

We should also be able to easily exclude classes from testing based on version support, although that also requires some functionality around this.

**Comment by lmmentel** [comment] 2022-05-18 21:38
> > we find a way of running a test suite without prophet
> 
> I would go with this: we introduce a `python_max_version` tag for estimators. I add a line of logic to the test suite (which already supports tag based selection) to exclude estimators that have a lower max version that current in the environment.
> 
> How about this?

I am strongly against that since it's not the role of the estimator to depend on the python version.

**Comment by fkiraly** [comment] 2022-05-19 23:34
> I am strongly against that since it's not the role of the estimator to depend on the python version.

I´m surprised about this statement of yours!

I see `sktime` like a library of libraries. I.e., estimators, many of which interface to other libraries. Those libraries have python version bounds. So it seems natural to attach that property to an estimator.

Note, in my conceptual model I do not consider an estimator to be an algorithm in its abstract, ideal form. I consider it an algorithm in a specific implementation. E.g., ARIMA from statsmodels is a different estimator from ARIMA from statsforecast. Similar to how you have different implementations of linear regression, while the "ideal" form is the same.

As python version compatibility is a property of the implementation, and my conceptual model refers to to an implementation, I think that it is very natural.

**Comment by fkiraly** [comment] 2022-05-19 23:36
Another, more practical argument for my viewpoint: in the "ideal limit", the number of algorithms following the sktime interface (though, not necessarily in sktime itself), or more generally, a scikit-learn like interface, approaches infinity.

In this limit, the individual libraries interfaces will be arbitrarily behind the current python version, e.g., slow to update. That will mean that as sktime grows, it would become more and more difficult to upgrade to newest python, which seems absurd.

**Comment by jlopezpena** [comment] 2022-06-01 10:06
Prophet recently merged a PR removing the `pystan` dependency (switching to `cmdstan` as a default backend). I have successfully built that version of prophet under python 3.10, so it should fix the issues discussed above. An "official" version has not been released yet, but you can specify the dependency straight to the github repo for testing purposes in the meantime

**Comment by fkiraly** [comment] 2022-06-01 18:08
thanks, @jlopezpena! But, that would not solve the same issue with `esig` and other soft dependencies, I feel we need a more general solution where `sktime` can move up in version even if some of the soft dependencies are stuck.

**Comment by lmmentel** [comment] 2022-06-12 14:31
@jlopezpena could you share a link to the wheels you've build? Which platforms have you build them for?

**Comment by fkiraly** [comment] 2022-07-01 19:11
> after removing them I get 42 warnings and 4 errors:

I'm 90% sure, that's because it is trying to construct classes that internally import the missing packages. We've isolated the soft dependency import to class constructors and methods, and the testing framework constructs those classes, including those with missing/incompatible imports.

@lmmentel, @jlopezpena, I'd really like to go with my solution of skipping those classes, based on python version present.
See here: https://github.com/alan-turing-institute/sktime/pull/2661

These more exotic packages will probably never update to 3.10, or, perhaps, only in the far future...

**Comment by fkiraly** [comment] 2022-07-02 21:26
>I guess the alternative would be to split the extras as separate extension packages, each with their own requirements and perhaps sharing the sktime namespace so that they can apply mixins as needed

Yes, that's also an option I like!
Having "satellite packages" rather than soft dependencies.

>Is that PR you mention "ready to go"? Will be happy to assist with testinng/buildinng if needed!

Hm, almost.
Let me look into it.

**Closed** 2022-07-09 21:40 UTC
Labels: maintenance, enhancement
