### ISSUE TITLE
Adding BSTS (Bayesian structural time series models) model via tensorflow_probability

### ISSUE THREAD

**Issue by aiwalter** [alan-turing-institute/sktime#612] opened 2021-01-12 10:47 UTC
**Is your feature request related to a problem? Please describe.**
I and @koralturkk would like to add a wrapper for forecasting with [BSTS](https://www.tensorflow.org/probability/api_docs/python/tfp/sts)
Examples are given [here](https://www.tensorflow.org/probability/examples/Structural_Time_Series_Modeling_Case_Studies_Atmospheric_CO2_and_Electricity_Demand#model_and_fitting).

**Describe the solution you'd like**

**Idea 1)**
Wrapping each possible [module](https://www.tensorflow.org/probability/api_docs/python/tfp/sts) via an argument of type `list` containing one or several `dict`.
For example: 
```python
tfp.sts.DynamicLinearRegression(
    design_matrix, drift_scale_prior=None, initial_weights_prior=None,
    observed_time_series=None, name=None
)
```
 ...would become 
```python
add_DynamicLinearRegression = [{
"design_matrix" = design_matrix,
"drift_scale_prior"=None, "initial_weights_prior"=None,
    "observed_time_series"=None, "name"=None}]
```

So this is also the way I was wrapping in `fbprophet` with `add_seasonality()` e.g.

**Idea 2)**
Allowing that the user creates the modules outside `sktime` so that it can be passed as a `tfp.sts` class:
```python
import tensorflow_probability as tfp
dlr = tfp.sts.DynamicLinearRegression(
    design_matrix, drift_scale_prior=None, initial_weights_prior=None,
    observed_time_series=None, name=None
)
```
We would need `**kwargs` for it to pass `dlr` in `sktime.BSTS(dlr)`

Looking forward for your feedback @mloning

**Comment by mloning** [comment] 2021-01-13 11:14
Hi @aiwalter and @koralturkk - this sounds like an interesting idea! I'm a little hesitant on adding TensorFlow Probability as a soft dependency because we had several issues with integrating it into the CI/CD workflows in other projects (sktime-dl especially). A may be a better idea to work on this in a companion repository. 

If this is something you're interested in, I'm happy to create one under the sktime organisation and give you admin rights. Since this would be a pure Python package, setting up CI/CD pipelines to check compatibility with the main repo shouldn't be too difficult either. 

Regarding the design: Could you show me what you have in mind for the user journey? How would models be encapsulated in a forecaster class?

**Comment by aiwalter** [comment] 2021-01-13 12:00
@mloning thx for feedback. Regarding design, `BSTS` works with components, so the user is free to add several of them to a model. In the following example, there are two components, `sts.LocalLinearTrend` and `tfp.sts.Seasonal`:
```python
def build_model(observed_time_series):
  trend = sts.LocalLinearTrend(observed_time_series=observed_time_series)
  seasonal = tfp.sts.Seasonal(
      num_seasons=12, observed_time_series=observed_time_series)
  model = sts.Sum([trend, seasonal], observed_time_series=observed_time_series)
  return model
```
So in `sts.Sum` the components are build together to one model. How to provide the user this flexibility comes back to the question above where I wrote down the 2 options I had in mind of how to deal with component. Basically this components will be given to `sktime.BSTS()` as arguments. The function `build_model` from the exmaple could be a part of the `_instantiate_model()` function.
Regarding adding this to `sktime`, I would propose we give it a try to get it running with CI. Now I have also @koralturkk to get it running on all platforms.

**Comment by fkiraly** [comment] 2021-01-13 12:23
Hm, regarding design:
I think aiming for *both* wrapped individual components and wrapped composites makes sense here! If I had to choose, I'd say to aim for wrapped composites, since that is more flexible and robust with regards to extensions and changes of `BSTS`.

The "really nice thing", design-wise, would be adding a compiler-like layer that recognizes when adjacent sktime components are from `BSTS` and replaces them by a wrapped (and more efficient) `BSTS` composite. But perhaps out of scope due to complexity...

Regarding dependencies: as @mloning says, one of these days, we need to fix how we manage the neural network package dependencies. Currently, we have no maintainer dedicated to that family of dependencies - it is quite some work to keep these spinning, so help would be very much welcome.
The problem is greater than just `BSTS`, it is essentially "anything that depends on tf", so it would be maintaining "time series models using deep learning packages".

**Comment by mloning** [comment] 2021-01-13 12:59
Ok, we can give it a try to integrate it into sktime! 

But we may have to make a difficult decision to not include it in the end, if we need to touch too much of the CI/CD pipeline, and move it to a separate repo. I worry about the extra maintenance burden for the CI/CD pipelines when upgrading versions later on. We have had similar issues with other packages already (e.g. the ongoing work to integrate the signature-based module).

**Comment by aiwalter** [comment] 2021-10-16 22:32
Closing as we have now `UnobservedComponents` which seems to be similar

**Comment by fkiraly** [comment] 2021-10-17 10:24
is it? I'd consider it a different estimator.

**Comment by fkiraly** [comment] 2021-10-17 13:28
Yes, I have no problems removing "Bayesian" from anything, but just on the conceptual level it's a different algorithm and estimator - as you just confirm.

So I think it's still a reasonable aspiration to have the Bayesian variant interfaced, and strictly speaking it's not addressed by having an interface to `UnobservedComponents`.

**Comment by mloning** [comment] 2021-12-03 23:02
Added this to the wish list and closed the issue since we won't be implementing this via tensorflow.

**Closed by mloning** 2021-12-03 23:02 UTC
Labels: interfacing algorithms, module:forecasting
