### ISSUE TITLE
[DOC]"ValueError: all input arrays must have the same shape" 

### ISSUE THREAD

**Issue by mgorjis** [alan-turing-institute/sktime#717] opened 2021-03-04 16:55 UTC
#### Describe the issue linked to the documentation
 When applying a classifier to my time series (converted to suitable nested format), I got this error:

`ValueError: all input arrays must have the same shape`

I think the issue is that all of my rows in time series doesn't have the same length. In fact, each row is measurements of a patients, and their lengths are different

**Comment by mloning** [comment] 2021-03-15 13:27
Hi @mgorjis, our classifiers currently don't support variable-length data, you could reshape it into equal-length data using padding, truncation or interpolation for example.

**Comment by mloning** [comment] 2021-03-15 13:27
I'll close this for now.

**Closed by mloning** 2021-03-15 13:27 UTC
Labels: documentation

**Comment by pedropalb** [comment] 2021-12-16 04:36
Hi, @mloning!

I’ve got the same error using a transformer created by `make_row_transformer(Imputer())`. The input data was a nested DataFrame containing series of variable length. Is it the currently expected behavior in this case? 

As the transformer created by this function operates independently on each row, I thought it would work. Why is it needed to force the series to have the same length?

From the top of my head, I would say that it is due to efficiency purposes (operations over the axis=1 of numpy arrays). But, in this case, you could check if the lengths match. If they do, coerce to numpy. Otherwise, proceed to process each series independently.

Does it make sense?

Thanks for the great work you’ve been doing!

**Comment by fkiraly** [comment] 2021-12-31 13:57
@pedropalb, apologies, I did not spot your message in a closed issue.

Generally, you don't need to have the time series being of same length, but some estimators may enforce that.

What you describe is a known problem, @pedropalb, so we've decided to get rid of `make_row_transformer` and have transformers cast/apply automatically per series if a `Panel` object like a nested dataframe is passed.

That is, the current refactor of transformers should allow the `Imputer` to be *directly* applied to any `Panel` format (including nested data frames) and not require equal length, without applying the `make_row_transformer`.

You may have to wait for https://github.com/alan-turing-institute/sktime/pull/1795 to merge, but you can try it out on your use case by checking out the PR to see whether it works. In fact, it would be appreciated to have an early user test, whether it works in your case.
