### ISSUE TITLE
[ENH] Grid Search for Global Models

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#2477] opened 2022-04-14 15:01 UTC
It looks like Grid Search is not enabled on Global Forecasting yet (no support for multi-index). I was wondering if this is planned. For example, I would like to be able to run the global model, but tune the hyperparameters of the regressor. I was wondering if this is planned for the future? Thanks!

Details here: https://nbviewer.org/gist/ngupta23/138f55d72f2764b47711c97a73de631d

```python
kwargs = WindowSummarizer.get_test_params()[0]

forecaster = make_reduction(
    RandomForestRegressor(max_depth=100),
    scitype="tabular-regressor",
    transformers=[WindowSummarizer(**kwargs)],
    window_length=None,
)

fh = np.arange(1, 13)

from sktime.forecasting.model_selection import ExpandingWindowSplitter, ForecastingGridSearchCV
cv = ExpandingWindowSplitter(fh=np.arange(1, 13))
param_grid = {"estimator__max_depth" : [100, 200, 300]}
gscv = ForecastingGridSearchCV(
    forecaster=forecaster,
    param_grid=param_grid,
    cv=cv)

try:
    # y_grouped is multiindex (2 levels)
    gscv.fit(y_grouped)
    y_pred = gscv.predict()
except NotImplementedError as e:
    print(e)
```
```python
<class 'pandas.core.indexes.multi.MultiIndex'> is not supported for input, use one of (<class 'pandas.core.indexes.range.RangeIndex'>, <class 'pandas.core.indexes.period.PeriodIndex'>, <class 'pandas.core.indexes.datetimes.DatetimeIndex'>, <class 'pandas.core.indexes.timedeltas.TimedeltaIndex'>) instead.
```

**Comment by fkiraly** [comment] 2022-04-14 15:48
Yes, indeed it's planned, it's the "next thing" in ensuring that hierarchical & probabilistic are integrated with compositors.

Duplicate of one of the items in here:
https://github.com/alan-turing-institute/sktime/issues/2243
so closing.

**Closed by fkiraly** 2022-04-14 15:48 UTC
Labels: enhancement

**Comment by fkiraly** [comment] 2022-04-14 15:50
(the metrics need to work first, and that depends on the abandoned metrics refactor https://github.com/alan-turing-institute/sktime/pull/1163 being picked up)
