### ISSUE TITLE
[BUG] KNeighborsTimeSeriesClassifier fails on Japanese Vowels data

### ISSUE THREAD

**Issue by zhangxjohn** [alan-turing-institute/sktime#1756] opened 2021-12-14 07:44 UTC
**Describe the bug**
ValueError                                Traceback (most recent call last)
/mnt/nfsroot/zhangxj/Data_Cache/workflows/ipykernel_91785/972100154.py in <module>
      2 
      3 clf = KNeighborsTimeSeriesClassifier()
----> 4 clf.fit(df_X, df_y)

~/anaconda3/lib/python3.8/site-packages/sktime/classification/distance_based/_time_series_neighbors.py in fit(self, X, y)
    196             Target values of shape = [n_samples]
    197         """
--> 198         X, y = check_X_y(
    199             X,
    200             y,

~/anaconda3/lib/python3.8/site-packages/sktime/utils/validation/panel.py in check_X_y(X, y, enforce_univariate, enforce_min_instances, enforce_min_columns, coerce_to_numpy, coerce_to_pandas)
    186     check_consistent_length(X, y)
    187 
--> 188     X = check_X(
    189         X,
    190         enforce_univariate=enforce_univariate,

~/anaconda3/lib/python3.8/site-packages/sktime/utils/validation/panel.py in check_X(X, enforce_univariate, enforce_min_instances, enforce_min_columns, coerce_to_numpy, coerce_to_pandas)
    107         # convert pd.DataFrame
    108         if coerce_to_numpy:
--> 109             X = from_nested_to_3d_numpy(X)
    110 
    111     return X

~/anaconda3/lib/python3.8/site-packages/sktime/datatypes/_panel/_convert.py in from_nested_to_3d_numpy(X)
    912     # If all the columns are nested in structure
    913     if nested_col_mask.count(True) == len(nested_col_mask):
--> 914         X_3d = np.stack(
    915             X.applymap(_convert_series_cell_to_numpy)
    916             .apply(lambda row: np.stack(row), axis=1)

<__array_function__ internals> in stack(*args, **kwargs)

~/anaconda3/lib/python3.8/site-packages/numpy/core/shape_base.py in stack(arrays, axis, out)
    425     shapes = {arr.shape for arr in arrays}
    426     if len(shapes) != 1:
--> 427         raise ValueError('all input arrays must have the same shape')
    428 
    429     result_ndim = arrays[0].ndim + 1

ValueError: all input arrays must have the same shape

**To Reproduce**
```python
from sktime.datasets import load_japanese_vowels
from sktime.classification.distance_based import KNeighborsTimeSeriesClassifier
df_X, df_y = load_japanese_vowels(split='train', return_X_y=True)
clf = KNeighborsTimeSeriesClassifier()
clf.fit(df_X, df_y)
```

Q: I found 'Japanese Vowels' dataset different different length for per instance, but  from_nested_to_3d_numpy() function can not convert nested DataFrame to 3d numpy, so fails to KNeighborsTimeSeriesClassifier().  What should I do?

**Comment by TonyBagnall** [comment] 2021-12-14 18:15
thanks for that, I actually noticed yesterday that this data is padded. KNN does not currently (yet) have the capability to handle unequal. KNN currently being fixed for the new distances and fit model https://github.com/alan-turing-institute/sktime/tree/numba_based_knn

**Comment by TonyBagnall** [comment] 2021-12-22 18:10
so the problem here is not a bug, but an enhancement request. KNN does not currently support classifying unequal length series. We are currently updating KNN to fit in with the new base classifier model and to use numba not cython. https://github.com/alan-turing-institute/sktime/issues/1713

**Comment by TonyBagnall** [comment] 2022-01-08 16:31
hi, the numba based knn has been merged into main, and the default tag is "capability:unequal_length": False, so I'll close this issue, feel free to raise a new one asking for the capability of KNN to handle unequal length series.

**Closed by TonyBagnall** 2022-01-08 16:31 UTC
Labels: bug, module:classification
