### ISSUE TITLE
[BUG] Updating in forecasting pipeline needs to transform data 

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#1381] opened 2021-09-03 15:09 UTC
**Describe the bug**
Currently, when calling `update` of a forecasting pipeline, the raw data is used for updating of all components. Instead, only the first transformer should be updated with the raw data. The subsequent components should receive the transformed data from the previous component. 

**Possible solutions**
* add a call to the transformer's `transform` method 
* additionally, introduce an `update_transform` shorthand in the base class which defaults to `self.update(...).transform(...)` similar to `fit_transform`

FYI @GuzalBulatova

**Comment by fkiraly** [comment] 2022-03-25 01:34
Closed in favour of the more recent bug report caused by this issue, https://github.com/alan-turing-institute/sktime/issues/2291

**Closed by fkiraly** 2022-03-25 01:34 UTC
Labels: bug, module:forecasting
