### ISSUE TITLE
Use of nested dataframes

### ISSUE THREAD

**Issue by MotoRZR** [alan-turing-institute/sktime#203] opened 2019-11-30 11:24 UTC
Is there any reason why the nested dataframe for input time series was selected?  It seems like a  clumsy way to deal with a time series especially in light of the fact that pretty much every other package expects data in tabular format so adds an extra step or two.  That said this is a great collection of tools.

**Comment by MotoRZR** [comment] 2019-11-30 12:48
Closing this as I’ve just seen the explanation elsewhere on here.  I still think a long format is better and more intuitive but it is what it is.  Current format will dissuade adopters I feel

**Comment by mloning** [comment] 2019-12-02 08:42
Thanks for your feedback, I agree the data container is not perfect at the moment, but long format isn't a good solution either for the purpose of modelling and evaluating machine learning techniques. You can find some more details on why we choose the nested format in our [wiki entry](https://github.com/alan-turing-institute/sktime/wiki/Data-representation-in-sktime). We're only in the process of considering alternative data representations, so it may change in the future.

**Comment by TonyBagnall** [comment] 2019-12-02 09:30
hi, I'll reopen this as its a valid discussion.

Nested series allows us to model multivariate unequal length series, and this is important for classification and regression. However, for tasks like forecasting I see no reason why they should not also handle different data structures. So in Java I would use method overriding, fit(OurDS x) and fit(AnArray x), but obviously this doesnt work in a language without typing. Switching is needed internally. That's a developers problem, and open to debate.

But this begs the question, is the data structure also a problem for the user? For the user, my approach would be to encapsulate, so the user has no need to see the data structure. So we can load from long format or  our own .ts or arff etc and the nested pandas approach would not really be apparent. I dont think we have done enough to make this seemless, but I also realize now that this is not the standard use case for most python/data science people, who seem to like interactive/enhanced spreadsheet use more than the batch mode I tend to employ.    

It seems to me the data structure is most confusing for forecasting, where you usually start with a single series, and using an n x m matrix of series seems daft. One solution may be to use a different underlying core representation for forecasting and classification/regression, with easy methods for converting from one to another.  The reduction methods then just return an appropriate data structure. This if I want to reduce simple forecasting to regression, I take a single series argument and return a one column matrix of series, panel forecasting might return a multiple column matrix?

**Comment by fkiraly** [comment] 2019-12-02 12:35
>One solution may be to use a different underlying core representation for forecasting and classification/regression

Yes, that's also a point I made in the discussions (that you didn't join :-( because you were busy).
The native function signatures should be using the most natural data representation *for the task*, rather than all tasks using the same data representation which implies strangeness for forecasting (on-cell-nested-data-frames).

This specific instance has already been changed though by @mloning .

**Comment by TonyBagnall** [comment] 2019-12-02 12:41
ah, I'm late to the party again! So I think we can close this issue again, as you seem to have it in hand and I am diving in without doing my prep :)

**Closed by TonyBagnall** 2019-12-02 12:41 UTC
Labels: enhancement

**Comment by fkiraly** [comment] 2019-12-02 12:44
I guess it will remain a recurring issue until we solve the data container question conclusively

**Comment by fkiraly** [comment] 2019-12-02 13:45
PS: by default, you're invited to all the parties.
