### ISSUE TITLE
[BUG] Upgrade of sktime crashed my KNeighborsTimeSeriesClassifier code

### ISSUE THREAD

**Issue by thomastkok** [alan-turing-institute/sktime#616] opened 2021-01-12 15:42 UTC
**Describe the bug**
Upgrade of sktime crashed my existing project which uses the KNeighborsTimeSeriesClassifier. It seems to me that there was no backwards compatibility in one of the recent upgrades for the project. (Or of course I am doing something wrong myself).

**To Reproduce**

```python
knn_model = KNeighborsTimeSeriesClassifier(n_neighbors=5, metric="dtw")
```

**Expected behavior**
I got the following error:
~/Documents/time_series_analysis/venv/lib/python3.8/site-packages/sktime/classification/distance_based/_time_series_neighbors.py in __init__(self, n_neighbors, weights, algorithm, metric, metric_params, **kwargs)
    167                 )
    168 
--> 169         super(KNeighborsTimeSeriesClassifier, self).__init__(
    170             n_neighbors=n_neighbors,
    171             algorithm=algorithm,

TypeError: super(type, obj): obj must be an instance or subtype of type

**Additional context**
This happened with the most recent upgrade I did.

**Versions**

System:
    python: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
executable: /home/thomas/Documents/time_series_analysis/venv/bin/python
   machine: Linux-5.8.0-36-generic-x86_64-with-glibc2.29

Python dependencies:
          pip: 20.0.2
   setuptools: 44.0.0
      sklearn: 0.24.0
       sktime: 0.5.1
  statsmodels: 0.12.1
        numpy: 1.19.4
        scipy: 1.5.4
       Cython: None
       pandas: 1.1.5
   matplotlib: 3.3.3
       joblib: 0.17.0
        numba: 0.52.0
     pmdarima: None
      tsfresh: None

**Comment by TonyBagnall** [comment] 2021-01-12 15:46
sorry about that, I'll look into it

**Comment by thomastkok** [comment] 2021-01-12 15:48
> sorry about that, I'll look into it

No problem at all, thanks a lot for the effort!

**Comment by thomastkok** [comment] 2021-01-12 15:51
@TonyBagnall apologies, it seems like I fixed this by updating sklearn as well. I did however get the following error:

ValueError: This KNeighborsTimeSeriesClassifier estimator requires y to be passed, but the target y is None.

However this is not the case, as I can show y to be the following:

[0 0 1 ... 0 0 0]

**Comment by TonyBagnall** [comment] 2021-01-12 15:54
have you synched to latest master for sktime? there was a change between scikit learn .23 and .24 which moved from allowing _fit(X) to requiring _fit(X,y) by default. However, we have now changed the tags and _fit(X) works for me.

**Comment by TonyBagnall** [comment] 2021-01-12 15:54
![image](https://user-images.githubusercontent.com/9594042/104338443-6cd85a80-54ee-11eb-9680-ab161b8a1e19.png)

**Comment by thomastkok** [comment] 2021-01-12 15:56
Thanks for your help, this might be inexperience on my parts but I installed with pip install --upgrade sktime. Is that not appropriate?

**Comment by thomastkok** [comment] 2021-01-12 15:57
Also, I am actually passing an y: that shouldn't be the problem. But I will try to work it out myself first, to not waste your time.

**Comment by TonyBagnall** [comment] 2021-01-12 15:58
ah it might not have updated on pip, I only pushed this yesterday, @mloning can you update it pip install? I think your code should work with the latest version.

**Comment by thomastkok** [comment] 2021-01-12 16:03
Amazing, thank you!

**Comment by thomastkok** [comment] 2021-01-13 09:48
For info: I manually added the more_tags function and this helped resolve the latter error of requiring y. However, this has caused me to once again get the first error as shown in the original post, which is thus still relevant.

**Comment by mloning** [comment] 2021-01-13 10:46
I've launched a new release just now, should be available via pip some time soon.

**Comment by TonyBagnall** [comment] 2021-01-13 10:50
thanks markus, lets see if its still broken after the update, I cannot reproduce the bug

**Comment by thomastkok** [comment] 2021-01-14 10:14
Thank you both for the assistance, I still get the following error:

```
~/Documents/time_series_analysis/venv/lib/python3.8/site-packages/sktime/classification/distance_based/_time_series_neighbors.py in __init__(self, n_neighbors, weights, algorithm, metric, metric_params, **kwargs)
    162                 )
    163 
--> 164         super(KNeighborsTimeSeriesClassifier, self).__init__(
    165             n_neighbors=n_neighbors,
    166             algorithm=algorithm,

TypeError: super(type, obj): obj must be an instance or subtype of type

```

For reference, my code is as simple as this:

```
        knn_ts = KNeighborsTimeSeriesClassifier(n_neighbors=k, metric="dtw")
        knn_ts.fit(
            sktime.utils.data_processing.from_3d_numpy_to_nested(x_train), y_train
        )
```

**Comment by TonyBagnall** [comment] 2021-01-14 19:29
I cant recreate this, the above works fine for me. The error python throws is not helpful, since KNeighborsTimeSeriesClassifier is definitely a subtype of KNeighborsClassifier. Perhaps there is something else you are including that causes the problem? Just googling, here are few random related problems

https://stackoverflow.com/questions/43751455/supertype-obj-obj-must-be-an-instance-or-subtype-of-type

https://stackoverflow.com/questions/32481508/autoreload-and-package-causing-typeerror-supertype-obj-obj-must-be-an-insta?noredirect=1&lq=1

https://stackoverflow.com/questions/23155140/typeerror-supertype-obj-when-running-pyprocessing-script-interactively/23158261

**Comment by TonyBagnall** [comment] 2021-02-17 22:09
hi, I'll close this now, feel free to raise a new issue if you are still having problems

**Closed by TonyBagnall** 2021-02-17 22:09 UTC
Labels: bug
