### ISSUE TITLE
[BUG] ColumnEnsembleClassifer can't be imported

### ISSUE THREAD

**Issue by dymax** [alan-turing-institute/sktime#2159] opened 2022-03-02 23:23 UTC
The provided code example gives an error as `ColumnEnsembleClassifier`  can't be imported

```
from sktime.classification.interval_based import DrCIF
from sktime.datasets import load_basic_motions
X_train, y_train = load_basic_motions(split="train")
X_test, y_test = load_basic_motions(split="test")
clf = DrCIF(n_estimators=10)
estimators = [("DrCIF", clf, [0, 1, 2, 3, 4, 5])]
col_ens = ColumnEnsembleClassifier(estimators=estimators)

```

**Comment by aiwalter** [comment] 2022-03-03 11:58
I guess you have to add an import for `ColumnEnsembleClassifier`?

**Comment by dymax** [comment] 2022-03-03 12:09
I tried to import the `ColumnEnsembleClassifier` form its `base classifier`  as shown below but still gets the error:

`from sktime.classification.composition import ColumnEnsembleClassifier`

**Comment by MatthewMiddlehurst** [comment] 2022-03-04 23:49
Hi, the correct package is compose, i.e. `from sktime.classification.compose import ColumnEnsembleClassifier`

```
from sktime.classification.compose import ColumnEnsembleClassifier
from sktime.classification.interval_based import DrCIF
from sktime.datasets import load_basic_motions

if __name__ == "__main__":
    X_train, y_train = load_basic_motions(split="train")
    X_test, y_test = load_basic_motions(split="test")
    clf = DrCIF(n_estimators=10)
    estimators = [("DrCIF", clf, [0, 1, 2, 3, 4, 5])]
    col_ens = ColumnEnsembleClassifier(estimators=estimators)
    col_ens.fit(X_train, y_train)
    print(col_ens)
```

I can run the above code without issue.

**Comment by fkiraly** [comment] 2022-03-05 08:40
Yes, looks like "not a bug" - sounds like the import was spelled incorrectly (which explains the failed import).

**Comment by MatthewMiddlehurst** [comment] 2022-03-18 15:21
Closing this. If there are any other related issues, feel free to re-open.

**Closed by MatthewMiddlehurst** 2022-03-18 15:21 UTC
Labels: bug, module:classification
