### ISSUE TITLE
Listing Forecasters to be Refactored

### ISSUE THREAD

**Issue by thayeylolu** [alan-turing-institute/sktime#1007] opened 2021-06-21 15:40 UTC
https://github.com/alan-turing-institute/sktime/issues/955
We need to slowly re-factor all forecasters to be compliant with the new interface (see PR #912). i.e., no overrides of fit etc and descendant classes only implementing core logic, while the BaseForecaster implements check etc logic.

Currently this is running due to various downwards compatibility workarounds, which should be removed once all forecasters are ready (in "no-override" state)

The forecasters that still need a downstream refactor are:
- _Forecasters in Italic text are failing test or CI_
- [X]  Forecasters checked have been merged
-  **Forecasters in Bold text are in progress and have not been merged**

- [X]   _NaiveForecasters_  
- [ ]    _EnsembleForecaster_
- [ ] **MultiplexForecaster**
- [ ] _TransformedTargetForecaster_
- [ ]  **_Reducer and related code**
- [ ]  _StackingForecaster_
 - [ ]   ForecastingGridSearchCV, RandomizedGridSearchCV, and BaseGridSearch
- [ ] OnlineEnsembleForecaster and descendants
- [ ]  _PmdArimaAdapter and descendants ARIMA, AutoARIMA
- [ ] BATS, TBATS, and _Tbatsadapter
 - [ ] _StatsModelAdapter and descendants AutoETS, ExponentialSmoothing, ThetaForecaster
 - [ ]  _HCrystalBallForecaster_
- [ ]   **Prophet and _ProphetAdapter**
 - [ ]  _PolynomialTrendForecaster_

**Comment by fkiraly** [comment] 2021-06-21 16:11
this is a duplicate of #955.

**Closed by fkiraly** 2021-06-21 16:11 UTC

**Comment by Lovkush-A** [comment] 2021-06-21 16:45
@fkiraly @thayeylolu I think Taiwo created this because we can't edit your checkboxes in #955. (at least, I know that I cannot adjust them).

To get around this, I created checkboxes in the hackmd file for forecasting group of 2021 dev days. https://hackmd.io/84rpzQEiQiWQy5oQjs7FYw?view. The checkboxes are at the bottom of the hackmd file

It this is not a suitable solution, let me know

**Comment by fkiraly** [comment] 2021-06-21 17:27
ah - well, I can simply update the checkboxes whenever a PR related to the root issue is closed?
