### ISSUE TITLE
extending existing estimators to samples of unequal length time series

### ISSUE THREAD

**Issue by DmitriyValetov** [alan-turing-institute/sktime#230] opened 2020-03-10 19:09 UTC
Hello.

I have found that some methods raise errors if I feed unequal sized time-series datasets into them.
My task is to train a classifier on unequal sized decreasing traces of optimization processes to catch an early stop (that's for motivation). I'll try to fix them and make a pull request if successful.

**Comment by mloning** [comment] 2020-03-11 16:09
Hi, thanks again for reaching out! Do you have a particular algorithm in mind that you want to extend to handle unequal-length series?

**Comment by fkiraly** [comment] 2020-03-11 22:56
As @mloning says, it would be good if you could state which estimators/methods this affects and which you are going to work on, as well as how your fix would look like (as algorithm or formula).

Would you mind explaining?

An important discussion point would be what type your fix is:
(a) a transformer which applies to all methods that don´t work for unequally spaced series? 
(b) a custom modificiation of a specific method?
(c) a bugfix?

Because in case (b) you would become the "owner" of the modified method - it might be improved, but it is a "new" one. In (c) the original maintainer remains the owner, since it is just an error fix. In (a) you would write a transformer.

On this it also depends where your code would go.

**Comment by DmitriyValetov** [comment] 2020-03-12 15:25
Agree.

First I looked at ShapeletTransformClassifier, which lead me into the ShapeletTransform class. Where I found that a few changes can make it work with unequal sizes. 
Changes at ShapeletTransform are:
1) another way of feeding ShapeletTransform.zscore. Used "np.array([dim[cand_start_pos: cand_start_pos + cand_len] for dim in X[series_id]])" instead of "X[series_id][:,cand_start_pos: cand_start_pos + cand_len]". An the same trick with other ShapeletTransform.zscore calls.
This fixes slicing time series, if they are of different sizes, X has [samples_n, features_n] shape, where X[0, 0] will be time series with other than X[1, 0] or X[0, 1] sizes. Our matrix is no longer fully rectanglar.
2) tried another condition in the comparison cycle with respect for shorter series.

Now I've noticed that there is a restriction on equality of series sizes among series in a sample, but I haven't run into this because my series are 1-dimensional.

If I understood @(fkiraly) right, this is for (a).

But also, I'm interested in adapting TimeSeriesForestClassifier.

**Comment by fkiraly** [comment] 2020-03-12 21:49
I see - so it`s a bugfix, or an extension to a transformer (not a classifier). I´m not sure which it is, but according to the register
https://github.com/alan-turing-institute/sktime/blob/dev/ESTIMATOR_OVERVIEW.md
the owner of shapelet transform is @jasonlines .

@jasonlines , would the proposed change be a genuine extension (new method), or a fix, in your opinion?

**Comment by fkiraly** [comment] 2020-03-12 21:52
Regarding time series forest, I believe there are two versions of it: one which is a composite, and one which is an atom. 

I assume you propose to do some transformation at the start?

@mloning , for the composite, which parts would have to get updated to be compatible with unequal length series?

We should probably put the composite (as code) in the table too.

**Comment by mloning** [comment] 2020-03-13 09:05
For time series forest, the random interval segmentation would have to be adapted. 
* For the modular version, this happens in the [RandomIntervalSegmenter](https://github.com/alan-turing-institute/sktime/blob/4dabe1afee0ad180f31c5f585f904f515ab4d0b1/sktime/transformers/segment.py#L113). 
* For the hard-coded one, it happens in the [fit](https://github.com/alan-turing-institute/sktime/blob/4dabe1afee0ad180f31c5f585f904f515ab4d0b1/sktime/classifiers/interval_based/tsf.py#L84) and transform method. @TonyBagnall any thoughts on changing the hard-coded version, I know it reproduces the bake-off, so perhaps we want to leave it untouched?

**Comment by TonyBagnall** [comment] 2020-03-13 09:19
hi, sorry for being late to this. Jason implemented the ShapeletTransform, so he will respond. But logically, it should be pretty easy to generalise for unequal length, and it would be a reall good thing to do. We have around 20 or so problems like this, and it has been high on my wish list for some time.

**Comment by TonyBagnall** [comment] 2020-03-13 09:21
so I think the logic of ST is this
randomly generate a shapelet candidate.
   1. Pick a random series
   2. Pick a random start point
   3. pick a random length
this should all work with unequal length series, hopefully already

**Comment by TonyBagnall** [comment] 2020-03-13 09:27
once you have selected a random candidate, you need to evaluate it. This involves 
1. running the candidate over every other season to find the distance to the nearest neighbour. 
2. storing the min distances for all series
3. Assess how well these distances split the data
(2) and (3) remain the same. Step 1 is the same, except for an edge case: what if the candidate is longer than the series being evaluated? Other two need no change. One way to handle the edge case is to simply reverse it: Given candidate S and series X, 
    if(|S|<|X|)
          minDist(S,X)
   else
          minDist(X,S) 
I havent thought about this much, but it seems a reasonable first approach. Not their are data characteristics that would influence the efficacy of this approach i.e. why are are series unequal length? Is it different sampling rates, different experimental stop time, start and stop time etc

**Comment by fkiraly** [comment] 2020-03-15 20:04
@DmitriyValetov , while waiting for @jasonlines , it probably makes most sense to work towards a PR that modifies the existing estimators - @mloning , what do you think?

**Comment by DmitriyValetov** [comment] 2020-03-20 11:08
> 
> 
> so I think the logic of ST is this
> randomly generate a shapelet candidate.
> 
>     1. Pick a random series
> 
>     2. Pick a random start point
> 
>     3. pick a random length
>        this should all work with unequal length series, hopefully already

Here is a problem: if two time series have rather different sizes ~ 2 times, there is a real probability of a such collision: 1) a start point from base candidate may be out of the indices range for another candidate, or 2) start point + chosen length may be also out of the range. So extending ShapeletTransformClassifier was not evident for me.

Some time after figuring this out + my experiense in computer vision tasks - I tought, may I resize time series? my time serieses are of different length, but describes similar events nearly fully. Images are resized before been feeded to NN, even if NN is of convolutional type (that makes resizing not obligatory). That made possible to use all methods as they are. Accurasy for my synthetic dataset was about 85-90% (confuson matrix also well).

Returning to ShapeletTransformClassifier, may be we can use resizing before launching the method? or use resizing during the method fit-predict time to synchronize start point and length of shapelet?

**Comment by jasonlines** [comment] 2020-03-30 18:48
Hi @DmitriyValetov, sorry for the delay - it has been been a bit crazy over the last couple of weeks!

If I understand your issue correctly then I think it's potentially more of a research question of how to handle this - to create a valid transform in the short term however then I think you would need to set a `max_shapelet_length` rather than using the default value. In terms of the shapelet transform, the candidates that are generated will always be valid themselves (i.e. will not overrun the series that they are produced from), but it may be important to set other parameters when using data of significantly differing lengths to make sure that matches are always possible between candidate shapelets and other series. 

When producing the candidate shapelets within the transform, each candidate shapelet is sampled from a series ID to extract it from and starting position. A length parameter is then also sampled, but this cannot exceed the shapelet length (so will be dependent on the specific series and starting position). While this will produce a valid candidate, it could potentially be longer than a whole other series if the user has a dataset with series of significantly different lengths and the parameters have not been set to prevent this - which I believe could be the problem that you are describing. 

In this case, it would be advisable to set the max_shapelet_length parameter of the transform to be that of the shortest series in your dataset. By default, the max length of a shapelet is unrestricted and is only bound by the length of the series that a shapelet is extracted from; if you have series that could be shorter than this though (which would be the case with many variable-length problems) then it would be necessary to set the maximum shapelet length to make sure that this doesn't happen.

I hope that helps and if I've misunderstood your issue/you are setting the max shapelet length appropriately and it's still not working, then please just give me a shout and I'll have another look

Thanks,

Jason

**Comment by DmitriyValetov** [comment] 2020-04-03 12:40
Good day.

The idea of manual or auto-estimate appropriate max_shapelet_length will prevent from index out of range exception, but we may lose the "scaling" factor or just strict us to use too short shapelets length. Am I right that we suppose that each of ingoing time series describes the same event fully? Here is a picture as a description of the approach that solved my problem: 
![sktime](https://user-images.githubusercontent.com/27976850/78355106-d0277a80-75b5-11ea-80d5-5070516130ce.png) 

I suppose it will work in case of sequences with different numbers of points (lengths of time series) with an assumption, that sequence fully describes an event. It is a kind of data transformation before applying methods. This assumption can be taken into account another way - while watching a comparison for the candidate rescale cand_len with the size of comparison this way: 

`comparison = ShapeletTransform.zscore(X[i][:,start_left: start_left+ int(cand_len*len(comparison )/this_series_len]))` 

this will effectively rescale comparison.

But maybe, my tending to rescaling doesn't match with datas' assumptions that were made before constructing sktime methods.  May you took an assumption like: input sequences of numbers are same by timeline and have same scale, they may describe the classes events not fully, but at real and equal (equally in all sequences) _time-scale_? I think it is near the truth.

**Comment by fkiraly** [comment] 2020-04-10 07:46
From what you explain, @DmitriyValetov , to me this sounds like a transformer that you would use in a Pipeline before using existing estimators.

How about implementing the following transformers or similar, all of which take a series and time stamps to rescale to:
* TSinterpTrafo - Selection of interpolation method by string, e.g., "carryforward", "average_of_closest"
* TSforecasterInterpTrafo - wraps a forecaster and does the same, interpolating via the forecaster
* TSregressorInterpTrafo - wraps a sklearn regressor, regresses value on time and uses that to interpolate

Is this the kind of method you were thinking about?

**Comment by DmitriyValetov** [comment] 2020-04-14 19:18
Yes, something of that kind. 
Have made a pullrequest today.
There is a new file with resizing transformed and notebook that describes the problem it solves in examples directory.

**Comment by mloning** [comment] 2020-11-24 17:40
I'll close this for now noting that the idea to extend functionality to unequal length data is on our roadmap #228

**Closed by mloning** 2020-11-24 17:40 UTC
Labels: implementing algorithms
