### ISSUE TITLE
[ENH] Upgrading to numpy 1.20

### ISSUE THREAD

**Issue by Ha5hBr0wn** [alan-turing-institute/sktime#1794] opened 2021-12-22 21:53 UTC
sktime requires numpy <1.20. This severely limits its use in larger more modern projects. Moving to numpy 1.20 would help allow sktime to be used in more projects without causing dependency issues.

**Comment by fkiraly** [comment] 2021-12-22 23:00
Yes, agreed - I believe the bound is coming from facebook prophet, is that correct?

@lmmentel, @freddyaboulton, would we still have an upper bound on `numpy 1.19` if we move to `prophet` from `fbprophet`?
See also https://github.com/alan-turing-institute/sktime/issues/1631

**Comment by lmmentel** [comment] 2021-12-23 08:21
Similar issue is also raised in #1787. I'm more than happy to look into it once we have the refactored CI/CD pipeline merged since it'll be easier to experiment with dependency versions.

**Comment by freddyaboulton** [comment] 2021-12-23 13:13
@fkiraly it was actually caused by pmdarima. They fixed the issue so I think it should be possible to unpin the numpy 1.19 constraint. 

https://github.com/alkaline-ml/pmdarima/issues/449

**Comment by freddyaboulton** [comment] 2021-12-23 13:20
The latest numba was also incompatible with the latest numpy (1.21) but looks like that will be fixed soon. 

https://github.com/numba/numba/issues/7339#issuecomment-997869862

**Comment by Ha5hBr0wn** [comment] 2021-12-23 21:48
Numba 0.54.1 is compatible with numpy 1.20.3 however. I don't know of a common machine learning package that requires higher than numpy 1.20 as of now

**Comment by lmmentel** [comment] 2021-12-23 22:51
I bumped numpy to `==1.20.1` and loosened up statsmodels to `>=0.12.1` and tried `pip-compile` for a quick check if the dependencies would resolve with `pip-compile` and they did :tada: 

Here is the `requirements.txt ` I got (linux with python3.9):

 ```
# This file is autogenerated by pip-compile with python 3.9
# To update, run:
#
#    pip-compile --extra=all_extras --extra=dev
#
--extra-index-url https://packagecloud.io/github/git-lfs/pypi/simple

attrs==21.2.0
    # via pytest
backports.entry-points-selectable==1.1.1
    # via virtualenv
certifi==2021.10.8
    # via requests
cfgv==3.3.1
    # via pre-commit
charset-normalizer==2.0.9
    # via requests
click==8.0.3
    # via distributed
cloudpickle==2.0.0
    # via
    #   dask
    #   distributed
    #   tsfresh
cmdstanpy==0.9.5
    # via fbprophet
convertdate==2.3.2
    # via
    #   fbprophet
    #   holidays
    #   workalendar
coverage[toml]==6.2
    # via pytest-cov
cycler==0.11.0
    # via matplotlib
cython==0.29.26
    # via
    #   fbprophet
    #   pmdarima
    #   pystan
    #   sktime (setup.py)
dask[dataframe]==2021.12.0
    # via
    #   distributed
    #   tsfresh
deprecated==1.2.13
    # via sktime (setup.py)
distlib==0.3.4
    # via virtualenv
distributed==2021.12.0
    # via tsfresh
dtw-python==1.1.10
    # via sktime (setup.py)
ephem==4.1.3
    # via lunarcalendar
esig==0.9.7
    # via sktime (setup.py)
execnet==1.9.0
    # via pytest-xdist
fbprophet==0.7.1
    # via sktime (setup.py)
filelock==3.4.0
    # via virtualenv
fonttools==4.28.5
    # via matplotlib
fsspec==2021.11.1
    # via dask
hcrystalball==0.1.10
    # via sktime (setup.py)
heapdict==1.0.1
    # via zict
hijri-converter==2.2.2
    # via holidays
holidays==0.11.3.1
    # via fbprophet
identify==2.4.0
    # via pre-commit
idna==3.3
    # via requests
iniconfig==1.1.1
    # via pytest
jinja2==3.0.3
    # via distributed
joblib==1.1.0
    # via
    #   pmdarima
    #   pyod
    #   scikit-learn
kiwisolver==1.3.2
    # via matplotlib
korean-lunar-calendar==0.2.1
    # via holidays
llvmlite==0.37.0
    # via numba
locket==0.2.1
    # via partd
lunarcalendar==0.0.9
    # via fbprophet
lunardate==0.2.0
    # via workalendar
markupsafe==2.0.1
    # via jinja2
matplotlib==3.5.1
    # via
    #   fbprophet
    #   hcrystalball
    #   matrixprofile
    #   pyod
    #   scikit-posthocs
    #   seaborn
    #   sktime (setup.py)
matrixprofile==1.1.10
    # via tsfresh
msgpack==1.0.3
    # via distributed
nodeenv==1.6.0
    # via pre-commit
numba==0.54.1
    # via
    #   pyod
    #   sktime (setup.py)
    #   stumpy
numpy==1.20.1
    # via
    #   cmdstanpy
    #   dask
    #   dtw-python
    #   esig
    #   fbprophet
    #   hcrystalball
    #   matplotlib
    #   matrixprofile
    #   numba
    #   pandas
    #   patsy
    #   pmdarima
    #   pyod
    #   pystan
    #   scikit-learn
    #   scikit-posthocs
    #   scipy
    #   seaborn
    #   sktime (setup.py)
    #   statsmodels
    #   stumpy
    #   tbats
    #   tsfresh
packaging==21.3
    # via
    #   dask
    #   matplotlib
    #   pytest
pandas==1.3.5
    # via
    #   cmdstanpy
    #   dask
    #   fbprophet
    #   hcrystalball
    #   pmdarima
    #   scikit-posthocs
    #   seaborn
    #   sktime (setup.py)
    #   statsmodels
    #   tsfresh
partd==1.2.0
    # via dask
patsy==0.5.2
    # via
    #   statsmodels
    #   tsfresh
pillow==8.4.0
    # via matplotlib
platformdirs==2.4.0
    # via virtualenv
pluggy==1.0.0
    # via pytest
pmdarima==1.8.4
    # via
    #   sktime (setup.py)
    #   tbats
pre-commit==2.16.0
    # via sktime (setup.py)
protobuf==3.11.2
    # via matrixprofile
psutil==5.8.0
    # via distributed
py==1.11.0
    # via
    #   pytest
    #   pytest-forked
pyluach==1.3.0
    # via workalendar
pymeeus==0.5.11
    # via convertdate
pyod==0.9.5
    # via sktime (setup.py)
pyparsing==3.0.6
    # via
    #   matplotlib
    #   packaging
pystan==2.19.1.1
    # via
    #   fbprophet
    #   sktime (setup.py)
pytest==6.2.5
    # via
    #   pytest-cov
    #   pytest-forked
    #   pytest-xdist
    #   sktime (setup.py)
pytest-cov==3.0.0
    # via sktime (setup.py)
pytest-forked==1.4.0
    # via pytest-xdist
pytest-xdist==2.5.0
    # via sktime (setup.py)
python-dateutil==2.8.2
    # via
    #   fbprophet
    #   holidays
    #   lunarcalendar
    #   matplotlib
    #   pandas
    #   workalendar
pytz==2021.3
    # via
    #   convertdate
    #   lunarcalendar
    #   pandas
pyyaml==6.0
    # via
    #   dask
    #   distributed
    #   pre-commit
requests==2.26.0
    # via tsfresh
scikit-learn==1.0.1
    # via
    #   hcrystalball
    #   pmdarima
    #   pyod
    #   sktime (setup.py)
    #   tbats
    #   tsfresh
scikit-posthocs==0.6.7
    # via sktime (setup.py)
scipy==1.7.3
    # via
    #   dtw-python
    #   hcrystalball
    #   matrixprofile
    #   pmdarima
    #   pyod
    #   scikit-learn
    #   scikit-posthocs
    #   seaborn
    #   statsmodels
    #   stumpy
    #   tbats
    #   tsfresh
seaborn==0.11.2
    # via
    #   scikit-posthocs
    #   sktime (setup.py)
setuptools-git==1.2
    # via fbprophet
six==1.16.0
    # via
    #   patsy
    #   protobuf
    #   pyod
    #   python-dateutil
    #   virtualenv
sortedcontainers==2.4.0
    # via distributed
statsmodels==0.13.1
    # via
    #   pmdarima
    #   pyod
    #   scikit-posthocs
    #   sktime (setup.py)
    #   tsfresh
stumpy==1.10.1
    # via
    #   sktime (setup.py)
    #   tsfresh
tbats==1.1.0
    # via sktime (setup.py)
tblib==1.7.0
    # via distributed
threadpoolctl==3.0.0
    # via scikit-learn
toml==0.10.2
    # via
    #   pre-commit
    #   pytest
tomli==2.0.0
    # via coverage
toolz==0.11.2
    # via
    #   dask
    #   distributed
    #   partd
tornado==6.1
    # via distributed
tqdm==4.62.3
    # via
    #   fbprophet
    #   tsfresh
tsfresh==0.19.0
    # via sktime (setup.py)
urllib3==1.26.7
    # via
    #   pmdarima
    #   requests
virtualenv==20.10.0
    # via pre-commit
wheel==0.37.1
    # via sktime (setup.py)
workalendar==16.2.0
    # via hcrystalball
wrapt==1.13.3
    # via deprecated
zict==2.0.0
    # via distributed

# The following packages are considered to be unsafe in a requirements file:
# setuptools
```

I will try to check if the deps resolution succeeds on different OS/python combinations.

**Comment by baggiponte** [comment] 2021-12-31 14:14
So what's the final verdict for the `numpy` version? Can it be a loosened constraint like `>=1.19`?

**Closed** 2022-01-24 19:25 UTC
Labels: maintenance
