### ISSUE TITLE
[ENH] Replace deprecated `pandas.Int64Index` with `pandas.Index`

### ISSUE THREAD

**Issue by khrapovs** [alan-turing-institute/sktime#2332] opened 2022-03-28 12:50 UTC
**Is your feature request related to a problem? Please describe.**

`pandas.Int64Index` is deprecated since pandas 1.4.0 and will be removed in 2.0. https://pandas.pydata.org/docs/reference/api/pandas.Int64Index.html

Now we get the warning:
```
FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead
```

**Describe the solution you'd like**

Replace with pandas.Index. https://pandas.pydata.org/docs/reference/api/pandas.Index.html

**Comment by fkiraly** [comment] 2022-03-28 13:52
Duplicate of #2049, closing #2049 in favour of this since it is better described here.

An attempt was already made by @gcchablani https://github.com/alan-turing-institute/sktime/pull/2082, it is probably abandoned.
Naive, ulk replace does not work, since we had used the type in type checking as well as type casting and type enforcement, replacing by `Index` is too permissive.

**Comment by fkiraly** [comment] 2022-03-28 13:52
... @aiwalter, maybe not a good first issue? As said, bulk replace does *not* work, and one needs to understand various intricate pieces of logic to get this fixed.

**Closed** 2022-04-04 20:18 UTC
Labels: good first issue, module:datatypes, enhancement
