### ISSUE TITLE
discussion: use of sktime/TSC for supervised binary label annotation of (possibly auto-correlated) multivariate time series

### ISSUE THREAD

**Issue by AASHISHAG** [alan-turing-institute/sktime#197] opened 2019-11-13 14:58 UTC
**Describe the bug**
I want to use SKTIME for multi variable binary TSC, i.e. I have multiple features (14) and I want to classify it as 0 or 1.

I have loaded a pre-processed dataset into as pandas dataframe and when I am trying to fit the model, I am getting exceptions like:

TypeError: object of type 'float' has no len()

Please refer my jupyter notebook for detailed log. I have tried all the techniques defined under example section of for multivariate time series classification. All reported error. 

https://github.com/AASHISHAG/time-series-classification/blob/master/sktime.ipynb

Is there something, that I am doing wrong? Any advice would be helpful.

>>> import platform; print(platform.platform())
Windows-10-10.0.18362-SP0
>>> import sys; print("Python", sys.version)
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.17.2
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.3.1
>>> import sktime; print("sktime", sktime.__version__)
sktime 0.3.0

**Comment by AASHISHAG** [comment] 2019-11-13 15:17
@mloning Thank you for the reply and references. I will definitely have a look. 

It is a meteorological dataset for past 20 years. Every row of the dataset represents the data for "a day". I have also uploaded the dataset for reference. 

https://github.com/AASHISHAG/time-series-classification

Can't I use sktime for data of such a kind?

**Comment by mloning** [comment] 2019-11-13 15:36
If the rows represent days, and you want to assign a label to each row, then the learning task is time series annotation (as defined in the linked paper above). 

Unfortunately, we don't support time series annotation yet, but it's something we want to cover eventually. Time series classification can in principle be used to solve a time series annotation task (by reduction), but this requires further data transformations to get the data into the right format.

**Comment by fkiraly** [comment] 2019-11-15 11:45
Perhaps the question is, what would the label be?

For the task of (vanilla) time series classification, you need training data in which each row is a pair of (i) a time series, and (ii) a classification label. 

The various methods then will fit a labelling algorithm that, given a time series in a test/deployment set, can assign a label, similar to the label assignment process on the training set.

Furthermore, the different pairs are assumed statistically independent, which might be a doubtful assumption in a generic meteorological setting (at least one that needs careful plausibility checking).

If you can describe what you want to do, we might be help diagnose which task you want, and whether it is currently supported by sktime.

**Comment by AASHISHAG** [comment] 2019-11-15 15:03
@fkiraly : The problem is from a medical setting.

Problem: Given a meteorological condition for the day, I want to predict whether a certain disease would occur or not. I have recordings for past 20 years for 14 features (temperature, pressure etc).

The labels are binary 0 or 1. The classes are imbalanced 0(80%) and 1(20%)

You can refer the dataset here: https://github.com/AASHISHAG/time-series-classification

I thought it to be as a time series classification problem and therefore, applied all traditional ML (random forest, xgboost, logistic regression, naive bayes) and DL (cnn, lstm,autoencoder) but couldn't find good results yet. Any advice on it would be helpful.

**Comment by fkiraly** [comment] 2019-11-15 15:46
Hm, this sounds like either TSC (very well supported), hierarchical/panel TSC (need to apply in certain way), or time series annotation (not supported yet, in dev).

The key differences lie in whether:
(a) measurements are from multiple patients/process, or a single patient/process. If yes: panel setting; if no: not a panel setting.
(b) the occurrence of the disease is plausibly autocorrelated, vs statistically independent over time granularity of days. That is, does it become more or less likely that the disease occurs on day x+1, if you additionally know that it had also occurred on day x (or not)? You can test for this by computing lagged autocorrelations of the disease label.

If the disease occurrence is auto-correlated, you can de-correlate it by aggregating at a range where independence is plausible.

In addition, you need to be careful to check for seasonality effects, e.g., by including the time of the year in models.

**Comment by fkiraly** [comment] 2019-11-15 15:47
PS: it would be easier to tell if you didn't only have the data table, but also a full *data dictionary* that descri bes what is in cols/rows of your data, how entries were recorded, etc.

**Comment by fkiraly** [comment] 2019-11-15 15:51
(removed bug label because I think we've concluded the behaviour is expected if you do not pass the expected data format for the respective task, i.e., not a bug)

**Comment by AASHISHAG** [comment] 2019-12-14 15:13
@fkiraly : Thank you, for the response. I possibly didn't get the update of your reply. I am checking now on autocorrelation and seasonality part.

Below are some insights about the problem and data:

1. It's weather data for ~20 years and the labels are recorded for multiple patients.
2. The rows in the data table represent a DAY, ordered in a sequence. 1 Jan, 2 Jan, 3 Jan ... for ~20 years.
3. The columns are weather features, like Temp, Pressure, Humidity etc.
4. The labels are 0 or 1.

I believe the occurrence of the disease is related to the past/future also. Therefore, I used LSTM's and also tried CNN's. But I got a ROC of 0.50. I think I should do some feature engineering on the data. I would appreciate if you could provide some guidance.

**Comment by fkiraly** [comment] 2019-12-18 10:26
Ok, what I would recommend in this case is to post here:
- length of the label series
- frequency of the label series (is this daily?)
- acf and pacf (plots) of the label series, you can get these from `pmdarima` from `acf` and `pacf`, plotting preceded by "plot_", in the  `utils` module

Note that if this is medical data (which I'm not sure about), you may not be legally allowed to post it here without having the necessary ethics approval and/or subject consent - legislation/regulation usually also applies for derived data such as the a auto-correlation (plots).

**Comment by AASHISHAG** [comment] 2019-12-20 13:33
Thank you @fkiraly for your advice. I have taken the approval on the data. I posted below the requested information:
> * length of the label series

Features: 15 Features + 1 added for Seasonality = 15 features (columns) [temp, weather, humidity, wind etc]
Labels: 0 or 1
6135 days (instances/rows)
Data (inital 2000 rows-for reference): https://github.com/AASHISHAG/time-series-classification/blob/master/pre_processed_data.csv

wind_max | wind_ave | rainfall_height | rainfall_form | sunny_hours | snow_height | bedeckungsgrades | dampfdruckes | luftdruck | humidity | air_temp_max | air_temp_min | temp | ground_temp_min | season | date | Bleeding
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
14.2 | 4.6 | 15 | 4 | 0.2 | 0 | 8 | 7.1 | 983.6 | 86 | 10.6 | -0.8 | 3.6 | -0.8 | 1 | 01-01-03 | 0
21.6 | 5.5 | 9 | 4 | 0.2 | 0 | 7.8 | 10.2 | 967.9 | 88 | 11.8 | 6.8 | 9.2 | 6 | 1 | 01-02-03 | 0
18.7 | 4.4 | 7.4 | 4 | 0 | 0 | 7.8 | 8.5 | 976.2 | 90 | 8.5 | 1.2 | 6.2 | 1 | 1 | 01-03-03 | 0
11 | 5.3 | 0 | 4 | 1.6 | 0 | 6.8 | 4.4 | 988 | 79 | 1.4 | -2.7 | -1.3 | -2.7 | 1 | 01-04-03 | 0
7.8 | 2.7 | 1.2 | 4 | 0.6 | 0 | 7.8 | 4.1 | 993.2 | 84 | -1.7 | -4.6 | -3.2 | -4.8 | 1 | 01-05-03 | 1

> * frequency of the label series (is this daily?)

Yes, from 01-01-03 to 29-06-19

> * acf and pacf (plots) of the label series, you can get these from `pmdarima` from `acf` and `pacf`, plotting preceded by "plot_", in the  `utils` module

Plots can be found here: https://github.com/AASHISHAG/time-series-classification/blob/master/acf_pacf.ipynb

**Comment by fkiraly** [comment] 2019-12-20 14:22
Alright, this is helpful.
I gather from your worksheet that there is *a single target time series*, that is, only one instance.

From the looks of it, thus, your vanilla task is:
- event modelling (because the "condition" happens rarely, and there are many days in-between without)
- with exogeneous variables that are time series

The standard approach for event modelling is temporal point processes, in this case you probably want one with an intensity function that is conditional on the past labels as well as the history of the exogeneous variables (= weather etc).
Your typical "nulls" are homogenous Poisson process (there is a constant event risk and it doesn't depend on the exogeneous variables) and inhomogenous Poisson process (event risk varies over time, but unrelated to anything).

This type of learning task is currently not supported by sktime (event modelling requires the skpro interface which is currently under major re-work by @jesellier). I'm also not sure whether there exists an off-shelf option for temporal point processes.

However, there may be some easy options to reduce to time series classification/regression, since it doesn't look like the label series is strongly auto-correlated, and the exogeneous variables seem to auto-correlate in the order of months (difficult to tell since you cut off the plots after a couple weeks):
- make monthly bins, and the label is the number of events in that month. Try to predict the number from the series in (probabilistic or deterministic) time series count regression.
- pair up "the past month of time series" with the label for that day (for all days), consider this a time series classification problem where you predict hte label for the day from the past month series.
- instead of the event 0/1 labels, consider the series of waiting times (time until next event). Pair up each waiting time with 1 month of series that leads up to the last event before the wait; try to predict the next waiting time by (probabilistic or deterministic) time series regression.

For evaluation, you have to keep in mind that the errors (samples of squared loss, classification loss) is not an independent sample. For comparisons to the baselines and dummys, you may have to correct critical differences for auto-correlation. A common effective sample size correction is "divide by 1+2*sum-over-acf" (acf not including the lag-0-term), this is under assumption of stationary residuals.

**Comment by fkiraly** [comment] 2020-01-07 09:48
Presuming this discussion has now concluded (please shout if not), closing the issue.
#210 is arising from this, and the specific tasks and reductions occurring here are subject of ongoing development.

**Closed by fkiraly** 2020-01-07 09:48 UTC
