### ISSUE TITLE
[BUG] Can't install on M1 Mac 

### ISSUE THREAD

**Issue by AlbertWh1te** [alan-turing-institute/sktime#2351] opened 2022-03-31 10:25 UTC
**Describe the bug**

I can't install this package on mac book pro M1 

**To Reproduce**

```bash
pip install sktime
```

**Expected behavior**

**Additional context**

**Versions**
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sktime/lib/python3.8/site-packages/sktime/classification/dictionary_based/__init__.py", line 13, in <module>
    from sktime.classification.dictionary_based._boss import BOSSEnsemble, IndividualBOSS
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sktime/lib/python3.8/site-packages/sktime/classification/dictionary_based/_boss.py", line 16, in <module>
    from numba import njit, types
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sktime/lib/python3.8/site-packages/numba/__init__.py", line 38, in <module>
    from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sktime/lib/python3.8/site-packages/numba/core/decorators.py", line 12, in <module>
    from numba.stencils.stencil import stencil
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sktime/lib/python3.8/site-packages/numba/stencils/stencil.py", line 11, in <module>
    from numba.core import types, typing, utils, ir, config, ir_utils, registry
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sktime/lib/python3.8/site-packages/numba/core/ir_utils.py", line 16, in <module>
    from numba.core.extending import _Intrinsic
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sktime/lib/python3.8/site-packages/numba/core/extending.py", line 19, in <module>
    from numba.core.pythonapi import box, unbox, reflect, NativeValue  # noqa: F401
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sktime/lib/python3.8/site-packages/numba/core/pythonapi.py", line 12, in <module>
    from numba import _helperlib
ImportError: numpy.core.multiarray failed to import

**Comment by fkiraly** [comment] 2022-04-05 23:34
@lmmentel, @freddyaboulton, any thoughts?

**Comment by lmmentel** [comment] 2022-04-06 07:05
Thanks for reporting this @AlbertWh1te. Could you share if you are using conda or vanilla pip? 

I don't think we have access to M1 and without that we're not going to able to reproduce the issue.

The error seems to be coming from numba/numpy so could you try to install just those two packages in a separate venv to help isolate the problem?

**Comment by EricLeer** [comment] 2022-04-07 19:26
@AlbertWh1te I have received a similar error (indeed from numba) using the [following link](https://numba.discourse.group/t/wheels-for-apple-silicon-m1/1282/2) I am able to install numba, after which I was able to succesfully install sktime using `pip install sktime` (all this on an m1 pro).

**Comment by lmmentel** [comment] 2022-04-07 19:47
Great! I'll close the issue then.

**Closed by lmmentel** 2022-04-07 19:47 UTC
Labels: bug

**Comment by fkiraly** [comment] 2022-04-07 19:48
So, reason for closing is, the culprit was the `numba` installation, not `sktime`?

We may want to add the advice to "frequent errors" on the installation page?

**Comment by lmmentel** [comment] 2022-04-07 21:14
Combination of M1 and numba. I expect that this will be a common pattern for M1 and any dependency that has a C extension requiring compiling and does now have dedicated wheels yet.

**Comment by renejra** [comment] 2022-05-09 19:22
While it was possible to install sktime, the module sktime-all-extras is not available for M1 and I'm seeing strange behaviors when following the notebooks of [sktime tutorial shown in PyData Berlin 2022](https://github.com/sktime/sktime-tutorial-pydata-berlin-2022) For example, not all forecasters are available, and I can't use the predict_var method for some reason.

**Comment by fkiraly** [comment] 2022-05-09 19:50
Hm, your strange behaviour sounds like using an older version of sktime, @renejra - what´s your local sktime version?

**Comment by renejra** [comment] 2022-05-09 19:53
@fkiraly I have 0.10.0 installed, build pyh27d4807_0 from conda-forge

**Comment by fkiraly** [comment] 2022-05-09 19:55
newest is 0.11.3, that would explain your problems...

**Comment by renejra** [comment] 2022-05-10 07:26
@fkiraly unfortunately newer version (0.11.3) faces dependency issues on M1 Macs. I'll keep debugging and give a heads up if I'm able to install sktime with all extras, and how I did it (if successful)

**Comment by renejra** [comment] 2022-05-22 18:42
Ok, so just wanted to leave my 2 cents on how to install sktime on a M1 Mac. Unfortunately there are many dependency errors, however I was able to install and run the latest version using Rosetta and old Intel packages. Generally, I would recommend (until dependecy errors are fixed in time):

1. Install `conda miniforge` for [Apple Silicon](https://github.com/conda-forge/miniforge), so whatever new environments you create, use distributions that build on top of the arm64 (M1) architecture. This is useful for other projects besides sktime.

2. Now you will want to create an environment that actually uses old packages for Intel (yes, the older architecture) which will still work thanks to Rosetta. You DO NOT need to install anything else. Run the commands below as [stated here](https://github.com/Haydnspass/miniforge#rosetta-on-mac-with-apple-silicon-hardware):

```bash
CONDA_SUBDIR=osx-64 conda create -n [environment]   # create a new environment
conda activate [environment]
conda env config vars set CONDA_SUBDIR=osx-64  # subsequent commands use intel packages
```

Done! You should be able to run `pip install sktime` or even `conda install -c conda-forge sktime-all-extras` and everything should work fine. Cheers!
