### ISSUE TITLE
extremely slow score/predict methods for sktime.classifier APIs 

### ISSUE THREAD

**Issue by nealgravindra** [alan-turing-institute/sktime#1039] opened 2021-06-23 23:58 UTC
**Describe the bug**

Slow (several minutes, without completion) computation when trying to predict or score time-series classifiers with `sktime.classification` APIs. Issue is not resolved even if the label dtype is modified (to object, float, int, etc.) even though example seems to use str type for labels (see input [4] [here](https://www.sktime.org/en/latest/examples/02_classification_univariate.html)).

**To Reproduce**
See code snippet below, with simulated data. 

```python
import numpy as np
from sktime.utils.data_processing import from_2d_array_to_nested
from sktime.classification.distance_based import KNeighborsTimeSeriesClassifier

# simulate data as sinusoid for 1000 samples, add white noise
t = np.linspace(0, 2*3.14, 2048)
x = np.repeat(np.sin(t).reshape(-1, 1), 1000, axis=1).T
x += np.random.uniform(0, 1, size=x.shape)

# convert to sktime data rep
X_train = from_2d_array_to_nested(x)

# init and fit model
clf = KNeighborsTimeSeriesClassifier()
dummy_binary = np.array(np.random.choice([0, 1], X_train.shape[0]), dtype=str)
clf.fit(X_train, dummy_binary)

# eval
clf.score(X_train, dummy_binary) # SLOW, does not complete computation
# clf.predict(X_train) # same problem as above
```

**Expected behavior**
The classifier fits in ms, and I expect the scoring/predict methods to be fast as well.

**Additional context**
Trying to do a multi-class classification problem with 1D time-series and ran into this bug while trying to get baselines using several classifiers from sktime. I thought it was an sklearn issue (perhaps related to [issue#10802](https://github.com/scikit-learn/scikit-learn/issues/10802)); however, when interrupted, the `clf.score(...)` method is stuck inside some `sktime` script after calling `clf.predict`, e.g., see tiny error snippets below for the cBOSS classifier:
```
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-258-f0a73361dd80> in <module>
     15 dummy_binary = np.array(np.random.choice([0, 1], X_train.shape[0]), dtype=str)
     16 clf.fit(X_train, dummy_binary)
---> 17 clf.score(X_train, dummy_binary)
     18 # clf.predict(X_train) # same problem as above

~/.local/lib/python3.8/site-packages/sktime/classification/dictionary_based/_cboss.py in predict_proba(self, X)
    254 
    255         for n, clf in enumerate(self.classifiers):
--> 256             preds = clf.predict(X)
    257             for i in range(0, X.shape[0]):
    258                 sums[i, self.class_dictionary[preds[i]]] += self.weights[n]
```

**Versions**
```
System:
    python: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
executable: /usr/bin/python3
   machine: Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.29

Python dependencies:
          pip: 20.0.2
   setuptools: 45.2.0
      sklearn: 0.24.2
       sktime: 0.6.1
  statsmodels: 0.12.2
        numpy: 1.20.3
        scipy: 1.4.1
       Cython: 0.29.23
       pandas: 1.2.4
   matplotlib: 3.2.1
       joblib: 1.0.1
        numba: 0.53.1
     pmdarima: None
      tsfresh: None
```

</details>

**Comment by fkiraly** [comment] 2021-06-24 21:15
assigned @tony because it's about TSC

**Comment by TonyBagnall** [comment] 2021-06-25 05:41
Slow relative to what? That's a relatively large data set. Distance measures are slow, especially in python, I may have mentioned how slow the language is once or twice.... This is not a bug, it is they claim a feature. Make series shorter and have fewer of them.

**Comment by TonyBagnall** [comment] 2021-06-25 05:45
Or use Euclidean as a distance measure (distance="Euclidean") I think it defaults to DTW. I believe George or chris has profiled this, found our DTW faster than other python DTW but slower than java

**Comment by TonyBagnall** [comment] 2021-06-25 05:58
Or use the RocketClassifier, that's the go to, fast, classifier.

**Comment by TonyBagnall** [comment] 2021-06-30 18:10
hi @nealgravindra can I close this issue, I'm afraid these algorithms are just slow on that size of data!

**Comment by nealgravindra** [comment] 2021-06-30 18:24
I still think it may be a bug. I'll respond in an hour more fully but the training is very fast, the inference is slow (I'll quantify with a follow-up post and test with standard knn clf distance metric). I wonder if the data type is part of the problem, as I haven't seen this used in any of the tutorials: `sktime.utils.data_processing.from_2d_array_to_nested`

**Comment by TonyBagnall** [comment] 2021-06-30 18:29
No rush happy to leave it open, just tidying up s bit

**Comment by nealgravindra** [comment] 2021-06-30 18:36
I totally understand and it may be me, for example, since I'm using an ipython kernel. I really appreciate the help

**Comment by fkiraly** [comment] 2021-06-30 18:58
but wait, @TonyBagnall, why would the scoring/prediction be slow? Typically, it's `fit` that should be the bottleneck, not `predict`.

**Comment by fkiraly** [comment] 2021-06-30 19:00
oh, it's k-neighbors! That would explain it, it's one of the rare cases of algorithms where the bottleneck is actually in the `predict`, since the "core" computations can only be carried out once the test data is known.

**Comment by fkiraly** [comment] 2021-06-30 19:04
yes, that's not a bug, it's a known property of the neighbors type algorithms.

There are ways to mitigate this (e.g., pre-building search spaces etc), but those are more experimental than the "standard implementation".

**Comment by fkiraly** [comment] 2021-06-30 19:06
>Trying to do a multi-class classification problem with 1D time-series and ran into this bug while trying to get baselines using several classifiers from sktime.

Regarding using `sklearn` classifiers as baselines, this is supported, but you should use the `Tabularizer` in a sklearn pipeline with the classifier, since you first need to convert the time series to the scikit-learn compatible format.

That would be sth we ought to add prominently in the tutorial for time series classification once we re-work it, @TonyBagnall - currently it shows only non-baseline methods.

**Comment by TonyBagnall** [comment] 2021-06-30 20:29
Nearest neighbour classifiers are lazy, so no fit time (if untuned) but longer predict time (o(nm^2) for n test cases length m)

**Comment by nealgravindra** [comment] 2021-06-30 22:02
The issue seems not to be limited to kNN classificiation with sktime classifiers. Below is some code to compare sklearn/sktime implementations with euclidean distance measures. I have to kill the program when using sktime's edit distance or dtw with the knn classifier after 5min. However, I am able to compare `sklearn_clf()` and `sktime_knn(distance='euclidean')`, which are both kNN classifiers using a euclidean distance measure. Both models both train very quickly (in ms) but the inference with the sktime implementation takes 46.2s, compared to 0.1s in sklearn's implementation. Trying another classifier, I also have to kill the shapelet model eval, even though the fit seems to be relatively fast. Code below illustrates this (with `#! NOTE`... indicating the problematic chunks).
```
import numpy as np
import time

def sim_data():
    # simulate data as sinusoid for 1000 samples, add white noise
    t = np.linspace(0, 2*3.14, 2048)
    x = np.repeat(np.sin(t).reshape(-1, 1), 1000, axis=1).T
    x += np.random.uniform(0, 1, size=x.shape)
    y = np.array(np.random.choice([0, 1], x.shape[0]), dtype=str)
    return x, y

def sktime_knn(x, y, distance='dtw'):
    import numpy as np
    from sktime.utils.data_processing import from_2d_array_to_nested
    from sktime.classification.distance_based import KNeighborsTimeSeriesClassifier

    # convert to sktime data rep
    X_train = from_2d_array_to_nested(x)

    # init and fit model
    clf = KNeighborsTimeSeriesClassifier(distance=distance)
    
    ## clock fit
    tic = time.time()
    clf.fit(X_train, y)
    print('... fit in {:.1f}-s'.format(time.time() - tic))

    # eval
    clf.score(X_train, y) # SLOW, does not complete computation
    # clf.predict(X_train) # same problem as above, also slow step in calling score method
    
    return clf

def sktime_clf(x, y, model='shapelet'):
    import numpy as np
    from sktime.utils.data_processing import from_2d_array_to_nested
    
    if model == 'shapelet':
        from sktime.classification.shapelet_based import ShapeletTransformClassifier
        clf = ShapeletTransformClassifier()
    else:
        print('TODO (enhancement): add other models')
    
    # convert to sktime data rep
    X_train = from_2d_array_to_nested(x)

    # clock fit
    tic = time.time()
    clf.fit(X_train, y)
    print('... fit in {:.1f}-s'.format(time.time() - tic))

    # eval
    clf.score(X_train, y) # SLOW, does not complete computation
    # clf.predict(X_train) # same problem as above, also slow step in calling score method
    
    return clf
    
def sklearn_clf(x, y):
    from sklearn.neighbors import KNeighborsClassifier

    ## ONLY DIFF: here, no conversion to sktime data rep
    X_train = x # not, `X_train = from_2d_array_to_nested(x)`

    # init and fit model
    clf = KNeighborsClassifier()
    
    # clock fit
    tic = time.time()
    clf.fit(X_train, y)
    print('... fit in {:.1f}-s'.format(time.time() - tic))

    # eval
    clf.score(X_train, y)
    
    return clf

# main

## get data
x, y = sim_data()

## clock comparable sklearn classifier
tic = time.time()
_ = sklearn_clf(x, y)
print('sklearn clf train/inf in: {:.1f}-s'.format(time.time() - tic))

## clock sktime classifiers
tic = time.time()
_ = sktime_knn(x, y, distance='euclidean')
print('sktime knn-euclidean train/inf in: {:.1f}-s'.format(time.time() - tic))

#! NOTE: here, I think there is a bug... I have to kill the program after 5min

## clock sktime classifiers
tic = time.time()
_ = sktime_knn(x, y, distance='erp')
print('sktime knn-erp train/inf in: {:.1f}-s'.format(time.time() - tic))

#! NOTE2: here also, I think there is a bug... I have to kill the program after 5min

## clock sktime classifiers
tic = time.time()
_ = sktime_knn(x, y, distance='dtw')
print('sktime knn-dtw train/inf in: {:.1f}-s'.format(time.time() - tic))

### other sktime clf'ers

#! NOTE3: here also, I think there is a bug... I have to kill the program after 5min

## clock sktime classifiers
tic = time.time()
_ = sktime_clf(x, y, model='shapelet')
print('sktime clf train/inf in: {:.1f}-s'.format(time.time() - tic))
```

**Comment by fkiraly** [comment] 2021-06-30 23:13
>The issue seems not to be limited to kNN classificiation with sktime classifiers.

Quick question for clarification: aren't your examples above still all variants of kNN?
It would be expected that these are substantially slower in `predict` than in `fit`.

**Comment by nealgravindra** [comment] 2021-06-30 23:27
I think the last call, `_ = sktime_clf(x, y, model='shaplet')` uses a RF classifier after finding shapelets? But I'm realizing this might be a bad one. Consider, 

```
import numpy as np
import time

def sktime_clf(x, y, model='shapelet'):
    import numpy as np
    from sktime.utils.data_processing import from_2d_array_to_nested
    
    if model == 'shapelet':
        from sktime.classification.shapelet_based import ShapeletTransformClassifier
        clf = ShapeletTransformClassifier()
    elif model == 'cboss':
        from sktime.classification.dictionary_based import ContractableBOSS
        clf = ContractableBOSS()
    elif model =='RF':
        from sktime.classification.interval_based import TimeSeriesForestClassifier
        clf = TimeSeriesForestClassifier()
    else:
        print('TODO (enhancement): add other models')
    
    # convert to sktime data rep
    X_train = from_2d_array_to_nested(x)

    # clock fit
    tic = time.time()
    clf.fit(X_train, y)
    print('... fit in {:.1f}-s'.format(time.time() - tic))

    # eval
    clf.score(X_train, y) # SLOW, does not complete computation
    # clf.predict(X_train) # same problem as above, also slow step in calling score method
    
    return clf

## clock sktime classifiers
tic = time.time()
_ = sktime_clf(x, y, model='RF')
print('sktime clf train/inf in: {:.1f}-s'.format(time.time() - tic))


```

**Comment by TonyBagnall** [comment] 2021-07-06 16:16
hi,

Euclidean distance is O(n), whereas all of the elastic distance measures are O(n^2) and this makes a huge distance. The distance functions are all implemented in cython and our experiments show they are equivalent or faster than other python implementations. I suggest you just use smaller datasets. Use rocket if you want a faster classifier or set the contract in ones that are contractable

**Comment by nealgravindra** [comment] 2021-07-07 01:50
It's clearly quite different on my tests depending on implementation for knn, c.f. `sktime` knn with euclidean dist metric to `sklearn` knn w/euclidean dist metric; `sktime` is over 40x slower at inference). Also the size of the data set is quite small (1000 samples, 2048 timepoints), see the simulation fx. Other `sktime` classifiers also have this problem, even contractable ones with small (<1min) time limits. Anyway, it seems there is nothing left to try so feel free to close the issue

**Comment by TonyBagnall** [comment] 2021-07-07 18:14
I'll ask @chrisholder to take a look as he is on top of distances

**Comment by TonyBagnall** [comment] 2021-07-14 20:06
hi, I've been looking at this and I think the problem is the pandas conversion. Internally, everything is pulled into numpy and we only use the pandas for unequal length series really. I see no reason why we should not accept 2D numpy for X, assuming each row is a single series, so I will just test this speed wise and use it a evidence to support my continued argument for this to be an allowable input format. Thanks.

**Comment by TonyBagnall** [comment] 2021-07-14 21:06
hi, I looked at this and you are right, something seems amiss, below 
fit time = 0.4911067485809326
 predict time = 0.45124173164367676
 score =  1.0
 fit time = 0.0
 predict time = 241.38946056365967
 score =  1.0
 fit time = 0.1250474452972412
 predict time = 203.24439430236816
 score =  1.0

I suspect that the cython versions are for some reason not being used, I will investigate further. Thanks 

import numpy as np
from sktime.utils.data_processing import from_2d_array_to_nested
from sktime.classification.distance_based import KNeighborsTimeSeriesClassifier
import time
from sklearn.neighbors import KNeighborsClassifier

if __name__ == "__main__":
    t = np.linspace(0, 2 * 3.14, 2048)
    X = np.repeat(np.sin(t).reshape(-1, 1), 1000, axis=1).T
    X += np.random.uniform(0, 1, size=X.shape)
    clf = KNeighborsTimeSeriesClassifier(distance="euclidean")
    c2 = KNeighborsClassifier(n_neighbors=1)
    dummy_binary = np.array(np.random.choice([0, 1], X.shape[0]), dtype=str)
    start = time.time()
    c2.fit(X, dummy_binary)
    fit = time.time()
    score = c2.score(X, dummy_binary)  # SLOW, does not complete computation
    pred = time.time()
    print(" fit time =", fit - start)
    print(" predict time =", pred - fit)
    print(" score = ", score)

    X_3d = np.expand_dims(X, axis=1)
    start = time.time()
    clf.fit(X_3d, dummy_binary)
    fit = time.time()
    # eval
    score = clf.score(X_3d, dummy_binary)  # SLOW, does not complete computation
    pred = time.time()
    print(" fit time =", fit - start)
    print(" predict time =", pred - fit)
    print(" score = ", score)

    x_panda = from_2d_array_to_nested(X)
    start = time.time()
    clf.fit(x_panda, dummy_binary)
    fit = time.time()
    score = clf.score(x_panda, dummy_binary)  # SLOW, does not complete computation
    pred = time.time()
    print(" fit time =", fit - start)
    print(" predict time =", pred - fit)
    print(" score = ", score)

**Comment by nealgravindra** [comment] 2021-07-16 02:20
Yeah, I was thinking cython versions OR the pandas conversion, which I can imagine is less than ideal. Thank you so much for checking, I really appreciate it!

**Comment by TonyBagnall** [comment] 2022-01-08 16:18
we have switched to numba, and our timing experiments show our distance functions are at least as fast (normally faster) than other implementations. I'll close this, but please do open a new issue if you still have the problem with the new distance measures

**Closed by TonyBagnall** 2022-01-08 16:18 UTC
Labels: module:classification

**Comment by nealgravindra** [comment] 2022-01-10 05:05
thank you so much, I really appreciate your commitment to fixing this. Cheers
