### ISSUE TITLE
[BUG] `ARIMA`, `ThetaForecaster`, `AutoETS`: `predict_interval` & `predict_coverage` give counterintuitive results

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#2275] opened 2022-03-22 10:43 UTC
**Describe the bug**

Some of these may be bugs and some may just need clarification.

1. ARIMA `predict_interval` produces wider intervals for lower coverage level compared to the higher coverage level
2. Quantile to alpha conversion seems to be inconsistent.
3. AutoETS predictions do not match the 50% quantile from `predict_quantiles`
4. Coverage to quantile conversion seems to be inconsistent.

**To Reproduce**

The entire code can be found here: https://gist.github.com/ngupta23/ab7e003de06ae5b919937c31b2bad179 with snippets below

```python
from sktime.datasets import load_airline
from sktime.forecasting.arima import ARIMA
from sktime.forecasting.theta import ThetaForecaster
y = load_airline()
```

## ARIMA 
```python
forecaster = ARIMA(order=(1, 1, 0), seasonal_order=(0, 1, 0, 12))
forecaster.fit(y, fh=[1,2,3])

forecaster.predict(return_pred_int=True, alpha=0.05)
forecaster.predict_quantiles(alpha=[0.025, 0.05, 0.1, 0.5, 0.9, 0.95, 0.975])
forecaster.predict_interval(coverage=[0.8, 0.9, 0.95])
```

![image](https://user-images.githubusercontent.com/33585645/159455224-202b4135-b20f-47ca-a8ac-88f4d1bbb018.png)

![image](https://user-images.githubusercontent.com/33585645/159455256-2121c932-25fa-4657-a38e-820191d97239.png)

![image](https://user-images.githubusercontent.com/33585645/159455279-3729d87e-9ada-45bd-a2aa-0ee8b3af6fc8.png)

### Observations

1. The 0.5 quantile from `predict_quantiles` matches with the forecast from `predict`. (Check pass)
2. ARIMA `predict_interval` produces wider intervals for lower coverage levels compared to the higher coverage level (Seems like a bug).
3. Intervals returned from `predict` with alpha = 0.05 seems to correspond to Quantiles = [0.025, 0.975] which is counter to this comment. Some clarification would be helpful) - https://github.com/alan-turing-institute/sktime/issues/2134#issuecomment-1049853020

> The "old" DEFAULT_ALPHA of 0.05 (alpha_low above) corresponds to a coverage of 0.9, and quantile points alpha_low = 0.05, alpha_high = 0.95.

4. Coverage of 0.9 does not match quantiles [0.05, 0.95]. Coverage of 0.95 does not match quantiles [0.025, 0.975]. (seems like a bug)

## Theta

```python
forecaster = ThetaForecaster(sp=12)
forecaster.fit(y, fh=[1,2,3])

forecaster.predict(fh=[1,2,3], return_pred_int=True, alpha=0.05)
forecaster.predict_quantiles(alpha=[0.025, 0.05, 0.1, 0.5, 0.9, 0.95, 0.975])
forecaster.predict_interval(coverage=[0.8, 0.9, 0.95])
```

![image](https://user-images.githubusercontent.com/33585645/159455827-892200b8-1ff2-497b-88c2-f773715eacae.png)

![image](https://user-images.githubusercontent.com/33585645/159455848-abfa42ce-0c3c-4126-80ad-dd2e674a1893.png)

![image](https://user-images.githubusercontent.com/33585645/159455895-32a32aae-ca44-4673-9cb2-29766d39b010.png)

### Observations

1. The 0.5 quantile from `predict_quantiles` matches with the forecast from `predict`. (Check pass)
2. ThetaForecaster `predict_interval` produces narrower intervals for lower coverage levels compared to the higher coverage level (Check pass).
3. Intervals returned from `predict` with alpha = 0.05 do not seem to correspond to any of the expected quantile levels (seems like a bug in one of the methods)

> The "old" DEFAULT_ALPHA of 0.05 (alpha_low above) corresponds to a coverage of 0.9, and quantile points alpha_low = 0.05, alpha_high = 0.95.

4. Coverage of 0.9 matches quantiles [0.05, 0.95] (pass)

## AutoETS

```python
forecaster = AutoETS(auto=True, n_jobs=-1, sp=12)
forecaster.fit(y, fh=[1,2,3])

forecaster.predict(fh=[1,2,3], return_pred_int=True, alpha=0.05)
forecaster.predict_quantiles(alpha=[0.025, 0.05, 0.1, 0.5, 0.9, 0.95, 0.975])
forecaster.predict_interval(coverage=[0.8, 0.9, 0.95])
```
![image](https://user-images.githubusercontent.com/33585645/159460483-84747439-bbc5-41d3-96b2-201ce21ac36b.png)

![image](https://user-images.githubusercontent.com/33585645/159460589-cc38001e-bdd5-4d53-b616-083ea3cb8ade.png)

![image](https://user-images.githubusercontent.com/33585645/159460690-5936a778-2b24-4507-9200-8c313eed2b25.png)

### Observations

1. The 0.5 quantile from `predict_quantiles` does not match with the forecast from `predict`. (Seems like a bug when compared to other models above)
2. AutoETS `predict_interval` produces narrower intervals for lower coverage levels compared to the higher coverage level (Check pass).
3. Intervals returned from `predict` with alpha = 0.05 do not seem to correspond to any of the expected quantile levels (seems like a bug in one of the methods)

> The "old" DEFAULT_ALPHA of 0.05 (alpha_low above) corresponds to a coverage of 0.9, and quantile points alpha_low = 0.05, alpha_high = 0.95.

4. Coverage of 0.9 does not match quantiles [0.05, 0.95]. Coverage of 0.95 does not match quantiles [0.025, 0.975].  (seems like a bug)

**Expected behavior**
Consistent behavior across the various forecasters.

**Versions**
<details>

System:
    python: 3.7.12 (default, Jan 15 2022, 18:48:18)  [GCC 7.5.0]
executable: /usr/bin/python3
   machine: Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic

Python dependencies:
          pip: 21.1.3
   setuptools: 57.4.0
      sklearn: 1.0.2
       sktime: 0.10.1
  statsmodels: 0.13.2
        numpy: 1.21.5
        scipy: 1.4.1
       pandas: 1.3.5
   matplotlib: 3.2.2
       joblib: 1.1.0
        numba: 0.55.1
     pmdarima: 1.8.5
      tsfresh: None

</details>

**Comment by fkiraly** [comment] 2022-03-23 00:08
Thanks!

This was indeed a bug, and a quite serious one.
It looks like it was caused by a typo/mistake in two formulae.
I think it is fixed now, and #2281 is on its way to be released in the next days with 0.11.0.

**Closed** 2022-03-23 09:25 UTC
Labels: bug
