### ISSUE TITLE
Relax "numpy==1.19.3" dependency 

### ISSUE THREAD

**Issue by TKassis** [alan-turing-institute/sktime#1914] opened 2022-01-23 02:42 UTC
**Is your feature request related to a problem? Please describe.**
Currently there is a hard dependency for numpy 1.19.3. Is this actually needed or is there room for newer numpy versions?

**Describe the solution you'd like**
Can this be relaxed to 1.20?

**Comment by lmmentel** [comment] 2022-01-23 07:59
Hi @TKassis, thanks for reporting this. We are currently working on this. There are already similar issues posted so we might close this and give another issue to track instead.

**Comment by fkiraly** [comment] 2022-01-23 09:16
duplicate of #1794, closing.
Yes, indeed this is sth we're working on, now that the CI/CD is upgraded.

**Closed by fkiraly** 2022-01-23 09:16 UTC
