### ISSUE TITLE
[BUG] Forecasting does not work with 10 minute interval data in PeriodIndex form

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#1876] opened 2022-01-14 14:58 UTC
**Describe the bug**
When data has a period index at 10 minute intervals, the prediction does not work.

Most likely related to 
Seems to be some issue with the indexing - most likely related to `ForecastingHorizon.to_absolute_int()` and how `integers` are computed.

```python
# Inside to_absolute_int, the following line does not seem to be giving the right integers
integers = absolute - start
```

**To Reproduce**
```python
import pandas as pd
from sktime.datasets import load_airline
from sktime.forecasting.exp_smoothing import ExponentialSmoothing
y = load_airline()

# Change index to 10 min interval
time_range = pd.date_range(
    pd.to_datetime("2019-01-01 00:00"), pd.to_datetime("2019-01-01 23:55"), freq="10Min"
)

# # Datetime Index works
# y.index = time_range

# Period Index does not work
y.index = time_range.to_period()

forecaster = ExponentialSmoothing(trend="add", seasonal="multiplicative", sp=12)
forecaster.fit(y, fh=[1, 2, 3, 4, 5, 6])
y_pred = forecaster.predict()
```

```python
File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\Nikhil\.vscode\extensions\ms-python.python-2021.12.1559732655\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\Nikhil\.vscode\extensions\ms-python.python-2021.12.1559732655\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\Nikhil\.vscode\extensions\ms-python.python-2021.12.1559732655\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\Nikhil\OneDrive\my_libraries\my_python_libraries\pycaret\pycaret_dev\time_series_debug.py", line 33, in <module>
    y_pred = forecaster.predict()
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\site-packages\sktime\forecasting\base\_base.py", line 242, in predict
    alpha=alpha,
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\site-packages\sktime\forecasting\base\adapters\_statsmodels.py", line 92, in _predict
    return y_pred.loc[fh.to_absolute(self.cutoff).to_pandas()]
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\site-packages\pandas\core\indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\site-packages\pandas\core\indexing.py", line 1153, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\site-packages\pandas\core\indexing.py", line 1093, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\site-packages\pandas\core\indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\site-packages\pandas\core\indexing.py", line 1374, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [PeriodIndex(['2019-01-02 00:00', '2019-01-02 00:10', '2019-01-02 00:20',\n             '2019-01-02 00:30', '2019-01-02 00:40', '2019-01-02 00:50'],\n            dtype='period[10T]')] are in the [index]"
```

**Expected behavior**
Should produce the right forecasts (6 future values at 10 minute intervals - i.e. [PeriodIndex(['2019-01-02 00:00', '2019-01-02 00:10', '2019-01-02 00:20', '2019-01-02 00:30', '2019-01-02 00:40', '2019-01-02 00:50'])

**Additional context**

**Versions**
<details>

System:
    python: 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\python.exe
   machine: Windows-10-10.0.19041-SP0

Python dependencies:
          pip: 21.1.3
   setuptools: 52.0.0.post20210125
      sklearn: 0.24.2
       sktime: 0.8.0
  statsmodels: 0.12.2
        numpy: 1.19.5
        scipy: 1.5.4
       Cython: 0.29.14
       pandas: 1.3.0
   matplotlib: 3.4.2
       joblib: 1.0.1
        numba: 0.53.1
     pmdarima: 1.8.2
      tsfresh: None

</details>

**Comment by fkiraly** [comment] 2022-01-14 19:49
@eenticott-shell, would you be able to have a quick look at this, whether this is already fixed by https://github.com/alan-turing-institute/sktime/pull/1830?

@ngupta23, this may be fixed but is not yet in the stable version. Have you tried wiht 0.9.0 or the dev version?

**Comment by ngupta23** [comment] 2022-01-14 23:29
@fkiraly

1. It is not working in v0.9.0 - https://gist.github.com/ngupta23/b447498e7b3955b79754c8ebc48efea2
2. I am unable to install it directly from GitHub to check the latest dev version - https://gist.github.com/ngupta23/ddf3276510f0ecf5933291cbe63043d0

**Comment by fkiraly** [comment] 2022-01-15 01:08
>I am unable to install it directly from GitHub to check the latest dev version - https://gist.github.com/ngupta23/ddf3276510f0ecf5933291cbe63043d0

That won't work due to the C dependencies - you have to follow the install instructions locally with build requirements if you want to try it:
https://www.sktime.org/en/stable/installation.html

We're working on removing the C dependencies soon so install is easier... but they are still there, sorry.

**Comment by ngupta23** [comment] 2022-01-19 21:13
@fkiraly I tested the `main` branch. It gives the same error

![image](https://user-images.githubusercontent.com/33585645/150214629-d0ab0353-abd9-4e4f-b9b0-a0c20655bb14.png)

**Comment by fkiraly** [comment] 2022-01-20 22:14
@ngupta23, I've confirmed the bug on python 3.9, windows, current dev.

I've also tried two other forecasters (naive and trend), and this error is *not* raised. This is, hence, possibly specific to the `statsmodels` adapter.

**Comment by fkiraly** [comment] 2022-01-20 22:18
This code seems to work as expected:
```python
from sktime.forecasting.base import ForecastingHorizon
fh=ForecastingHorizon([1, 2, 3, 4, 5, 6])
fh.to_absolute(cutoff = y.index[-1])
```
this gives
```ForecastingHorizon(['2019-01-02 00:00', '2019-01-02 00:10', '2019-01-02 00:20',
             '2019-01-02 00:30', '2019-01-02 00:40', '2019-01-02 00:50'],
            dtype='period[10T]', is_relative=False)```

**Comment by fkiraly** [comment] 2022-01-20 22:19
(so I guess it's not the same bug as you fixed, @eenticott-shell)

**Comment by ngupta23** [comment] 2022-01-22 00:30
@fkiraly It seems to be a more prevalent problem. I will try to list out specific issues.

## For statsmodels

The issue seems to be with `to_absolute_int` method of the ForecastingHorizon which is called from the adapter. At a 10 minute interval in PeriodIndex, it seems to be returning extremely large values for the integers.

![image](https://user-images.githubusercontent.com/33585645/150614706-a215f5cd-bdc6-4b7c-9994-bceeb68c700a.png)

## For PolynomialTrendForecaster

The issue seems to be with the calculation of X. It ends up with many more points because `_get_duration` does not seem to return the right number of points

![image](https://user-images.githubusercontent.com/33585645/150616436-5b4317f6-0398-4688-afa7-8c597e21d86e.png)

**Comment by eenticott-shell** [comment] 2022-01-24 11:13
> (so I guess it's not the same bug as you fixed, @eenticott-shell)

No it isn't, but I would be happy to take a look at it

**Comment by fkiraly** [comment] 2022-01-24 11:25
yes, @eenticott-shell, makes sense since you recently picked apart the `Forecasting Horizon` already

**Comment by ngupta23** [comment] 2022-01-24 14:06
Thanks @eenticott-shell. Documenting changes needed.

- [ ] fix in `to_absolute_int` in `ForecastingHorizon`
- [ ] fix in `_get_duration`

**Comment by fkiraly** [comment] 2022-02-09 14:28
This should be fixed by #1981.

**Closed** 2022-02-09 14:27 UTC
Labels: bug, module:forecasting

**Comment by ngupta23** [comment] 2022-02-09 15:50
Thank you @fkiraly, @eenticott-shell and @khrapovs.
Is it possible to add this to an incremental release like 0.10.1 or similar. If not, what would be the estimated release data for this fix?

Thanks!

**Comment by fkiraly** [comment] 2022-02-09 18:32
yes, we wanted to release 0.10.1 soon, due to scipy 0.18.0, e.g.,
https://github.com/alan-turing-institute/sktime/issues/1994
this will need some planning though, so possibly/probably mid-Feb

**Comment by ngupta23** [comment] 2022-02-24 12:39
Hi @fkiraly. Sorry for the delay. I checked it out and this works in 0.10.1. Thanks!
