### ISSUE TITLE
[DOC] TOC links broken in Forecasting user guide  

### ISSUE THREAD

**Issue by tmerrittsmith** [alan-turing-institute/sktime#3368] opened 2022-08-31 07:15 UTC
#### Describe the issue linked to the documentation
On this page https://www.sktime.org/en/stable/examples/01_forecasting.html, the Table of Contents hyperlinks do not match with the headers they refer to, so clicking on them does nothing.

#### Suggest a potential alternative/fix

Fix the links. Happy to fix the links for you - but I'm not sure how you're exporting the notebooks to docs? Is it markdown?

**Comment by fkiraly** [comment] 2022-08-31 18:01
Thanks for bringing this up! Help is appreciated!

The embedding of notebooks into the docs happens via these symbolic links here:
https://github.com/alan-turing-institute/sktime/tree/main/docs/source/examples

side note: strangely, not all the links seem to work currently - if you have an idea why that is, help would be appreciated. Perhaps running `symlink_examples.sh` here https://github.com/alan-turing-institute/sktime/tree/main/docs might resolve it (didn't do it for me, but might be the operating system)

**Comment by aiwalter** [comment] 2022-08-31 21:26
Duplicate of #2274

**Comment by fkiraly** [comment] 2022-09-02 16:30
well, that gives you the opportunity to close two issues for the price of one, @tmerritsmith!

**Closed by fkiraly** 2022-09-02 16:30 UTC
Labels: documentation
