### ISSUE TITLE
Forecasting multivariate time series in Sktime

### ISSUE THREAD

**Issue by SLTaiwo** [alan-turing-institute/sktime#871] opened 2021-05-14 18:50 UTC
Pls, I'll like to know how to handle forecasting in multivariate time series with sktime.
Let's say I have two time series variables energy load and temperature (or even including 3rd variable, var3) at hourly intervals and I'm interested in forecasting the load demand only  for the next 48hrs.
1- Would it suffice to treat this as a univariate time series forcasting by discarding the other variables (temperature and var3)?
2- If i want to keep both variables but forecast on energy load, how would this be treated with sktime?

**Update to this question:**
**@mloning** , you responded earlier that this could be treated as a univariate time series with exogenous variables.
Pls I'll like to know how I can implement this (with **multiple exogenous variables**) in sktime by reduction to tabularized features and using ML algorithms like decision tree , KNN regression etc.
I would like to compare the result with the statistical method like SARIMAX which I read (though not yet confirmed) that sktime also interfaces with.
Thanks

**Comment by mloning** [comment] 2021-05-14 22:23
Hi @SLTaiwo, could you post a minimal, reproducible example of what you have tried so far?

**Comment by mloning** [comment] 2021-05-15 10:46
Here's an example: 
```python
from sktime.forecasting.arima import AutoARIMA
from sktime.datasets import load_longley
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.forecasting.base import ForecastingHorizon
y, X = load_longley()
fh = ForecastingHorizon([1, 2, 3])
y_train, y_test, X_train, X_test = temporal_train_test_split(y, X, fh=fh)
forecaster = AutoARIMA()
forecaster.fit(y_train, X_train, fh=fh)
y_pred = forecaster.predict(X=X_test)
```

**Comment by fkiraly** [comment] 2021-05-15 18:47
FY, @SLTaiwo, (re-)designing multivariate forecasting will likely be one of the major topics at this summer's [sktime dev days](https://github.com/alan-turing-institute/sktime/issues/863) - feel free to sign up if you'd like to contribute.

**Comment by yunusrf** [comment] 2021-05-19 17:12
> Here's an example:
> 
> ```python
> from sktime.forecasting.arima import AutoARIMA
> from sktime.datasets import load_longley
> from sktime.forecasting.model_selection import temporal_train_test_split
> from sktime.forecasting.base import ForecastingHorizon
> y, X = load_longley()
> fh = ForecastingHorizon([1, 2, 3])
> y_train, y_test, X_train, X_test = temporal_train_test_split(y, X, fh=fh)
> forecaster = AutoARIMA()
> forecaster.fit(y_train, X_train, fh=fh)
> y_pred = forecaster.predict(X=X_test)
> ```
> 
> Reduction to cross-sectional regression works in the same way.

With the sample code getting the following error:
predict() got an unexpected keyword argument 'X'.

sklearn version : 0.24.2
sktime version :0.6.1

**Comment by mloning** [comment] 2021-05-19 17:26
@yunusrf I cannot reproduce this, it works for me on the same version. @SLTaiwo does it work for you or do you see the same error?

**Comment by yunusrf** [comment] 2021-05-19 17:31
> @yunusrf I cannot reproduce this, it works for me on the same version. @SLTaiwo does it work for you or do you see the same error?
![testing_multiple exogenous variables](https://user-images.githubusercontent.com/1234047/118857724-079fd600-b8e1-11eb-839d-6e1b52f7c087.png)

I may be missing something. Please see the snapshot of dev environment.

**Comment by mloning** [comment] 2021-05-19 19:45
@yunusrf looks like the error comes from `pmdarima` - which `pmdarima` version do you use?

**Comment by yunusrf** [comment] 2021-05-20 05:44
> @yunusrf looks like the error comes from `pmdarima` - which `pmdarima` version do you use?

Yes, you are correct. There was an issue with this package. Created a fresh environment and installed pmdarima-1.8.2. Code is working now. Thank you very much for your prompt reply. Appreciate hard work from the entire team.

**Comment by mloning** [comment] 2021-05-20 07:11
I close this issue now, @SLTaiwo please feel free to reopen if anything is still unclear.

**Closed by mloning** 2021-05-20 07:11 UTC

**Comment by SLTaiwo** [comment] 2021-05-21 10:43
@yunusrf, was fine for me. Thanks @mloning 

> 
> 
> > @yunusrf I cannot reproduce this, it works for me on the same version. @SLTaiwo does it work for you or do you see the same error?
> > ![testing_multiple exogenous variables](https://user-images.githubusercontent.com/1234047/118857724-079fd600-b8e1-11eb-839d-6e1b52f7c087.png)
> 
> I may be missing something. Please see the snapshot of dev environment.
