### ISSUE TITLE
More types of y_train can be included.

### ISSUE THREAD

**Issue by li-xin-yi** [alan-turing-institute/sktime#202] opened 2019-11-22 14:51 UTC
I was impressed by the sklearn interface used in sktime. So I thought it may be a good idea to use `sklearn.model_selection.RandomizedSearchCV` to do some hyperparameters tuning with specified dataset.

But I read documents of `sklearn.model_selection.RandomizedSearchCV` and `sktime`, with many attempts, I found a conflict occurred when CV in `sklearn` requires the parameter `y` in `fit` should support safe split used index set (e.g. something like `(train_indexes,test_indexs)`), where the index set (e.g. `[[...]]`) must make the corresponding y_train become a dataframe with shape `(1,1)` instead of a `pd.Series`.

I have not figured out any solution to deal with it so far. If such a dummy dataframe can be accepted as y_train, maybe some troubles will go away.

Can I add this feature in code and create a pull request?

**Comment by fkiraly** [comment] 2019-11-26 15:11
Hm, in the absence of an answer so far:
I assume your use case is forecasting? Since with the time series classification use case, `RandomizedSearchCV` should work without problems.

Currently, tuning methods for forecasting are still under development (and/or not available), since as you say you need temporal splits and you need to apply them to series.

However, if you use a supervised learner to forecast, you can apply tabular re-sampling schemes from sklearn by using, say time series splits and `RandomizedSearchCV` *inside* the `ReducedRegressionForecaster` that reduces forecasting to superised regression, i.e., your model specification code would look like 
`ReducedRegressionForecaster(RandomizedSearchCV(myFavouriteSupervisedLearner()))` plus parameter settings. The temporal re-sampling strategy would be an argument to `RandomizedSearchCV` in this composite.

If this is not wha you are looking for, would you mind explaining what you would like to do? E.g., is this for forecasting? If so, what would you like to tune and how? Perhaps with some example code?

**Comment by fkiraly** [comment] 2019-11-26 15:12
PS: @mloning would know about the most recent state of tuning in the forecasting use case.

**Comment by mloning** [comment] 2019-11-27 17:45
Assuming that you're interested in forecasting, we have a [ForecastingGridSearchCV](https://github.com/alan-turing-institute/sktime/blob/forecasting/sktime/forecasters/model_selection.py) class on the forecasting branch, but it's still experimental and more functionality has to be added. 

If you would like to try it out, you have to follow our [advanced installation instructions](https://alan-turing-institute.github.io/sktime/installation.html#development-version) to download and install the development version.

**Comment by li-xin-yi** [comment] 2019-11-28 02:26
can you provide any example about the usage of `RandomizedSearchCV` (or  `GridSearchCV`) in tutorials or documents in detail?

**Comment by mloning** [comment] 2019-11-28 12:02
I've added an experimental notebook [here](https://github.com/alan-turing-institute/sktime/blob/forecasting/examples/forecasting_gscv.ipynb), we hope to further develop and test this functionality over the next couple of weeks.

**Comment by fkiraly** [comment] 2019-11-28 12:11
... which means @mloning would be thankful for written feedback, suggestions, criticism, or formal testing of the experimental features. And/or pointing out what you were looking for in case this wasn't it.

**Comment by mloning** [comment] 2020-06-01 12:24
I close this issue for now, but please re-open if you're thinking about working on this!

**Closed by mloning** 2020-06-01 12:24 UTC
Labels: feature request
