### ISSUE TITLE
UserWarning: NotImplementedWarning: NaiveForecaster does not have a custom `update` method implemented. NaiveForecaster will be refit each time `update` is called.

### ISSUE THREAD

**Issue by muhlbach** [alan-turing-institute/sktime#843] opened 2021-04-27 13:33 UTC
In version 0.5.3, there was no problem calling the 'update' method using the NaiveForecaster. However, since version 0.6.0, I receive the following warning:

`UserWarning: NotImplementedWarning: NaiveForecaster does not have a custom `update` method implemented. NaiveForecaster will be refit each time `update` is called.`

The update method is important to bootstrap prediction intervals. When will this be available again?

**Expected behavior**
The expected behavior is that the model is not refit when 'update' is called.

**Additional context**

**Versions**
System:
    python: 3.8.8 (default, Apr 13 2021, 12:59:45)  [Clang 10.0.0 ]
executable: /Users/muhlbach/opt/anaconda3/envs/stable/bin/python
   machine: macOS-10.16-x86_64-i386-64bit

Python dependencies:
          pip: 21.0.1
   setuptools: 52.0.0.post20210125
      sklearn: 0.24.1
       sktime: 0.6.0
  statsmodels: 0.12.2
        numpy: 1.18.5
        scipy: 1.6.2
       Cython: 0.29.23
       pandas: 1.1.3
   matplotlib: 3.3.4
       joblib: 1.0.1
        numba: 0.50.1
     pmdarima: 1.8.0
      tsfresh: None

**Comment by muhlbach** [comment] 2021-04-27 13:39
I see that this problem is not limited to NaiveForecaster. I get the same error message for ARIMA. Have you removed the functionality of 'update'? Where can I find the release notes?

**Comment by aiwalter** [comment] 2021-04-27 14:06
I guess its not a bug, but rather an issue of UX. This was added by @pabworks in #660 . I think what is new is just a warning. The issue is mainly when doing a grid search because this warning will always warn for each fit, which can be annoying. Not sure how to handle this best, any ideas?
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Comment by muhlbach** [comment] 2021-04-27 14:09
But my impression is that now each model is refit once 'update' is called, but in the older versions that did not happen?

**Comment by mloning** [comment] 2021-04-27 15:12
@muhlbach could you describe what behaviour you expected when calling update? 

Update can mean several things: 
1. passing "now" information, i.e. the cutoff at which we want to make predictions,
2. passing new data,
3. updating fitted parameters based on new data. 

If you just want 1 and 2, you should be able to call `update(..., update_params=False)`.

If you also want 3, you need to call `update(..., update_params=True)` (the new default setting for `update_params`). 

Updating parameters like fitting parameters requires a separate model-specific algorithm, none of them are implemented at the moment. The default behaviour is therefore to fall back to refitting, which can still be seen as a form of updating, but may not be as efficient as bespoke update algorithms. We raise the warning to let users know that this is what's happening.

Are you aware of any toolbox that implements online-learning/update algorithms for common forecasting models? I'm not aware of many libraries that do that, e.g. statsmodels does not seem to support this (see this [post](https://stackoverflow.com/questions/66345248/partial-fit-or-incremental-learning-for-autoregressive-model#comment117297808_66345248)).

**Comment by mloning** [comment] 2021-05-06 16:46
I'll close this now, but feel free to reopen if you want to add anything.

**Closed by mloning** 2021-05-06 16:46 UTC

**Comment by muhlbach** [comment] 2021-05-11 01:32
@mloning, sorry I didn't get back to you in time. Setting `update_params=False` worked as a charm! For future reference, where can I find the changes you implement from version to version? I haven't been able to locate them online.

**Comment by mloning** [comment] 2021-05-12 18:45
Which landing page, on GitHub or on sktime.org? There is a static page here: https://www.sktime.org/en/latest/changelog.html but it's not automated and it doesn't link to GitHub, that's why I prefer the release notes on GitHub. I had a look a automation tools a while ago but didn't find anything to fully automate the process.

**Comment by fkiraly** [comment] 2021-05-13 15:54
@mloning, both landing pages, I guess? The tables at the top are the same, so I would just add "change log" or "latest release notes" to either. Static link to the static changelog.html should do the job cheaply.

Regarding automation, that could be a "good first issue" - don't know how one would do that, but surely there is someone out there who can do that six times before breakfast.

**Comment by mloning** [comment] 2021-05-14 08:44
Sure, feel free to add the link. We could also have something like a table of contents at the top.
