### ISSUE TITLE
Fitting ShapeletTransform fails with y = pandas.Series and non-default index [BUG]

### ISSUE THREAD

**Issue by prockenschaub** [alan-turing-institute/sktime#194] opened 2019-11-08 09:13 UTC
**Describe the bug**
`ShapeletTransform` (and `ContractedShapeletTransform`) throws an error if it is passed `y` as a `pandas.Series` with an index that is not a simple range (i.e. 0, 1, 2, 3, ...),

**To Reproduce**

```python
import pandas as pd
from sktime.datasets import load_gunpoint
from sktime.transformers.shapelets import ShapeletTransform
from sklearn.ensemble.forest import RandomForestClassifier
from sklearn.pipeline import Pipeline

X, y = load_gunpoint(split='TRAIN', return_X_y=True)

pipeline = Pipeline([
    ('st', ShapeletTransform(verbose=2)),
    ('rf', RandomForestClassifier(n_estimators=10)),
])

y = pd.Series(y)
y.index = pd.Int64Index([i + 1 for i in range(len(y))])
pipeline.fit(X, y)
# Key Error: 0
```

**Expected behavior**
I would expect that `y` is converted to a consistent representation within fit (e.g. `np.array`) that then does not rely on a pandas index.

**Versions**
<details>

Windows-10-10.0.17763-SP0
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
NumPy 1.17.2
SciPy 1.2.2
sktime 0.3.1

</details>

**Comment by mloning** [comment] 2019-11-13 15:19
Thanks again for raising the issue! Since you've fixed this already, if I remember correctly, as PR would be appreciated!

**Comment by prockenschaub** [comment] 2019-11-13 15:24
I haven't fixed that one in particular but rather converted `y` to `np.array` in my custom code. I can easily fix that in the ShapeletTransform. 

Do we have to look at this for other functions too? That is, is/should there a convention on how to treat `y`, e.g. by always converting to `np.array`?

**Comment by mloning** [comment] 2019-11-13 15:29
For classification/regression, converting it to numpy array should be fine. We just have to make sure that the subsequent code works expects arrays and not series. 

When fixing this, we should probably also make sure we validate the input using the functions [here](https://github.com/alan-turing-institute/sktime/blob/master/sktime/utils/validation/supervised.py).

**Comment by mloning** [comment] 2020-06-01 12:26
Should be fixed now with consistent input checks, see PR #246

**Closed by mloning** 2020-06-01 12:26 UTC
Labels: bug
