### ISSUE TITLE
[BUG] sktime.datatypes._panel._examples raises pandas.core.common.SettingWithCopyError

### ISSUE THREAD

**Issue by bobbys-dev** [alan-turing-institute/sktime#1452] opened 2021-09-24 22:28 UTC
**Describe the bug**
Attempting to install [tsai](https://pypi.org/project/tsai/) as an upstream package also installs this package, but the install raises an error that traces to line 67 in "/opt/conda/lib/python3.8/site-packages/sktime/datatypes/_panel/_examples.py"
```
    X.iloc[0][0] = pd.Series([1, 2, 3])
```

**To Reproduce**
Importing any code that executes the code starting at line 67 of /sktime/datatypes/_panel/_examples.py can raise a Pandas error, depending on Pandas version that may be installed

**Expected behavior**
No error should be raised on install or import of sktime as a dependency. 

**Additional context**

**Versions**
System:
    python: 3.9.1 (default, Sep 16 2021, 11:42:30)  [Clang 12.0.5 (clang-1205.0.22.11)]
executable: /.../.pyenv/versions/3.9.1/bin/python
   machine: macOS-11.6-x86_64-i386-64bit

Python dependencies:
          pip: 21.2.4
   setuptools: 49.2.1
      sklearn: 1.0
       sktime: 0.8.0
  statsmodels: 0.12.2
        numpy: 1.20.3
        scipy: 1.7.1
       Cython: None
       pandas: 1.3.3
   matplotlib: 3.4.3
       joblib: 1.0.1
        numba: 0.53.1
     pmdarima: None
      tsfresh: 0.18.0

**Comment by fkiraly** [comment] 2021-09-25 09:50
Thanks for reporting!

I'm trying to reproduce the bug with your specified python and pandas version but can't - the lines seem to run fine, and installation as well.

Would you kindly be able to post your full error message/traceback?

**Comment by fkiraly** [comment] 2021-09-25 09:52
Further, if you get the error, it seems plausible that - before installing `sktime` - the following might be a minimally reproducible example of the root cause:

```
cols = [f"var_{i}" for i in range(2)]
X = pd.DataFrame(columns=cols, index=[0, 1, 2])
X.iloc[0][0] = pd.Series([1, 2, 3])
```

Could you kindly check whether these three lines run or not, in your environment *before* installing `sktime`?
If not, what is the error message/traceback?

**Comment by oguiza** [comment] 2021-09-26 10:20
Hi, 

I'm one of core developers of tsai. I've noticed this issue, and have digged into it. I've temporarily fixed the issue in `tsai`.
Here's what I found: 

- the issue doesn't occur with pandas 1.1. It occurs with pandas 1.3. 
- this code works well: 

```bash
import sktime
import pandas as pd
cols = [f"var_{i}" for i in range(2)]
X = pd.DataFrame(columns=cols, index=[0, 1, 2])
X.iloc[0][0] = pd.Series([1, 2, 3])
```

    So this operation is allowed by pandas.

- However, in tsai  fastai was imported before sktime. fastai applies a patch to pandas that causes the issue: 

```bash
import pandas as pd
from fastcore.basics import patch

if not hasattr(pd.DataFrame,'_old_init'): pd.DataFrame._old_init = pd.DataFrame.__init__

@patch
def __init__(self:pd.DataFrame, data=None, index=None, columns=None, dtype=None, copy=False):
    if data is not None and isinstance(data, Tensor): data = to_np(data)
    self._old_init(data, index=index, columns=columns, dtype=dtype, copy=copy)
    
cols = [f"var_{i}" for i in range(2)]
X = pd.DataFrame(columns=cols, index=[0, 1, 2])

X.iloc[0][0] = pd.Series([1, 2, 3])
```
 
   this works up to pandas 1.1, but fails with 1.3. 

IMO, the issue is not caused by sktime. It's caused by fastai. 

I've temporarily changed the order of imports to avoid the issue. But a more permanent fixed is required. I have created an issue with fastai (https://github.com/fastai/fastai/issues/3485).

**Comment by fkiraly** [comment] 2021-09-26 10:51
Well, that explains why we couldn't reproduce the bug.

Personally, I'd still be happy to apply the fix if it prevents the error for anyone also using `fastai`, @bobbys-dev, since all that matters is the identity of the object created in the example, and not how.

PS: I think it's really really a bad idea to apply patches to a cornerstone package like `pandas` in a downstream package (and not in `pandas` itself), since exactly sth like this happens and you can't figure out what's going on...

**Comment by fkiraly** [comment] 2021-09-26 10:54
closing the issue since it's not a bug.

@bobbys-dev, would still appreciate the PR if you can resolve the merge issues.

@oguiza, the code you just pasted is quite painful to look at ... probably you want to try resolve this upstream issue in `fastai` 😄

**Closed by fkiraly** 2021-09-26 10:54 UTC
Labels: bug

**Comment by bobbys-dev** [comment] 2021-09-26 20:02
Thank you @fkiraly and @oguiza for the insight. I have the related PR for your development team.
